### ISSUE TITLE
Add bad_words_ids for [

### ISSUE THREAD

**Issue by finetuneanon** [KoboldAI/KoboldAI-Client#10]
Saw some people talking about how sometimes author's notes leak into generated text with KoboldAI. Huggingface transformers has a built in logit bias function that lets you blacklist the offending bracket tokens. Might be a useful option to include. There's some code for it in my notebook for example.
https://github.com/finetuneanon/gpt-neo_dungeon/blob/main/gpt-neo_dungeon.ipynb?short_path=5056482#L239

**Comment by KoboldAI** [comment]
Added the bad_word_ids to the local generator call in today's patch, will update the Colab notebook shortly. Thanks for the info!

**Comment by finetuneanon** [comment]
Thanks for adding it quickly, but it seems lke [ can still leak. Might be necessary to add some more of these.

```
Bad keys: ['Ġ[*]', 'Ġ[[', 'Ġ[+]', 'Ġ[/', 'Ġ[(', '":["', '[/', '>[', '[_', 'Ġ([', '":[{"', 'Ġ][', '[]', 'Ġ//[', 'Ġ[...]', 'Ġ<[', '.[', '".[', 'Ġ[âĢ¦]', '[', '][/', '[[', '."[', 'Ġ[+', 'Ġ[', 'Ġ[];', '=[', ',[', "Ġ['", '][', 'Ġ[*', ').[', '],[', ')[', "['", '([', 'Ġ[|', '":[', 'Ġ[]', 'Ġ[&', ':[', '["', '"[', "Ġ'[", 'Ġ["', '-[', 'Ġ"[', 'Ġ[-'] (Count: 48)
Bad ids: [[17912], [26894], [47527], [18161], [38381], [36937], [42669], [44926], [49074], [685], [16410], [26076], [17816], [25915], [38430], [21737], [3693], [29342], [29565], [30109], [49082], [41832], [44438], [42924], [12878], [20598], [14692], [47175], [41888], [17635], [36338], [29795], [23834], [26358], [14631], [30138], [49146], [32509], [13412], [17414], [26933], [33250], [58], [46581], [37250], [31161], [7131], [25787]]
```

**Comment by KoboldAI** [comment]
Yeah, I noticed when I went to do the colab version that your implementation created a much longer list of tokens to filter. I'll try to push these through at work today.

**Comment by KoboldAI** [comment]
Added the full suite of vocab containing "[" to the bad_words_ids parameter in tonight's push. Let me know if AN continues to leak.
