### ISSUE TITLE
Implement typical sampling 

### ISSUE THREAD

**Issue by RenegadeX91** [KoboldAI/KoboldAI-Client#104]
Hi, just wanted to say that I really like the project and it's what I've been missing since the guys over at AI Dungeon hampered their AI.
I've been watching some recent developments in the field of NLP and this paper https://arxiv.org/abs/2202.00666 caught my attention.
This paper in particular goes over how using typical sampling results in a lot more natural or human like responses over just using top k sampling.

Looks like this code in particular does the typical sampling https://github.com/cimeister/typical-sampling/blob/3e676cfd88fa2e6a24f2bdc6f9f07fddb87827c2/src/transformers/generation_logits_process.py#L242-L272

I ran transformers with this change implemented and it does seem to be a lot better at generating more human like text.
Now I'm not much a programmer myself so I can't fork it and implement it so I was wondering if this is a feature that you guys could possibly look into adding, thank you.

**Comment by henk717** [comment]
I have merged VE's commit, you can test this out on the United version available on the official Colab's (Make sure to select it prior to clicking play) and in the update-koboldai.bat script.

**Comment by RenegadeX91** [comment]
I used it with 0.2 as suggested in the paper with all of the 16GB models.
I get much fewer responses that feel robotic so I would say it's doing its job.
Many thanks for implementing it.

**Comment by henk717** [comment]
This is now upstreamed.
