### ISSUE TITLE
ColabKobold SSL error?

### ISSUE THREAD

**Issue by Derpford** [KoboldAI/KoboldAI-Client#107]
When I try to launch a ColabKobold TPU instance, I get the following error:
> # Secure Connection Failed
> 
> An error occurred during a connection to template-toner-bookstore-berkeley.trycloudflare.com. SSL received a record that exceeded the maximum permissible length.
> 
> Error code: SSL_ERROR_RX_RECORD_TOO_LONG
> 
>    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>    Please contact the website owners to inform them of this problem.

**Comment by henk717** [comment]
The SSL certificate is beyond our control simce its the certificate of trycloudflare itself. I did look up the error and it seems malwarebytes users can have this. So if you have malwarebytes see if you can tinker with it to the point it lets you access trycloudflare links.

**Comment by Derpford** [comment]
I don't use malwarebytes. Is it possible this is an issue on cloudflare's end?

**Comment by henk717** [comment]
Its possible but more likely to be an issue with either your browser or a security product being unable to handle the certificate. If it is on cloudflares end it should get fixed over time.

**Comment by Derpford** [comment]
The problem has persisted.

**Comment by henk717** [comment]
Which operating system and browser are you using? Nobody else has ran into the issue so it seems to be local to your device.

**Comment by Derpford** [comment]
Firefox, on Windows.

**Comment by Derpford** [comment]
It should be noted that on Chrome, I still get an error: ERR_SSL_PROTOCOL_ERROR.

**Comment by moehydrogen** [comment]
Hmm... So is this why we shifted to localtunnel? >_<

**Comment by henk717** [comment]
> Hmm... So is this why we shifted to localtunnel? >_<
That one was mostly because Cloudflare has a lot of moments where it goes down, gives 1033 errors and antiviruses block it for people. So it was never the most reliable experience. Nobody gave me bad feedback about Localtunnel so far, so if you have issues with it its important i know so i can make the right decisions for the future of colab.

**Comment by moehydrogen** [comment]
> 

I will make sure to set the UA on the *.loca.lt domain to something strange (with my creativity for sure). For censorship-related reasons, that "this is a tunnel site" alert is slow to load for me.

**Comment by henk717** [comment]
For now you could also expand the code and remove the --localtunnel parameter so it uses cloudflare again. In the future i can make it a drop down if that helps.

**Comment by Derpford** [comment]
Where exactly is the `--localtunnel` parameter? I'm struggling to find it. I'm also not sure localtunnel was in use by the colab I was using.

**Comment by henk717** [comment]
Its only in the development colab available at https://henk.tech/colabkobold13b after moe's feedback its now just a choice on the page so people can choose what they prefer.

**Comment by Derpford** [comment]
I just tested with the development colab, and I do *not* get the error when running with localtunnel. It's exclusively a problem when running via cloudflare.

**Comment by moehydrogen** [comment]
> I just tested with the development colab, and I do _not_ get the error when running with localtunnel. It's exclusively a problem when running via cloudflare.

Hmm, it seems we each have encountered **independent** problems when running with cloudflare (your case) / localtunnel (my case)... You may just choose localtunnel, then, I guess

**Comment by henk717** [comment]
Localtunnel is now upstreamed giving people the choice they need, since I can't control the SSL certificates on their end I recommend just using the one that works for you.
