### ISSUE TITLE
low_cpu_mem_usage crash

### ISSUE THREAD

**Issue by memaddr** [KoboldAI/KoboldAI-Client#109]
Hey, I have the weirdest error when trying to load 6B models. I have tried Janeway and Shinen, both are consistently crashing (after a few minutes) with the following trace:
```
Looking for GPU support...FOUND!
Initializing Flask... OK!
Initializing transformers, please wait...
Traceback (most recent call last):
  File "aiserver.py", line 981, in <module>
    model     = AutoModelForCausalLM.from_pretrained(vars.model.replace('/', '_'), cache_dir="cache/", **lowmem)
  File "/install_dir/KoboldAI-Client/venv/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/install_dir/KoboldAI-Client/venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1880, in from_pretrained
    cls._load_pretrained_model_low_mem(model, loaded_state_dict_keys, resolved_archive_file)
  File "/install_dir/KoboldAI-Client/venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2168, in _load_pretrained_model_low_mem
    new_val = state_dict[k].to(param_dtype)
KeyError: 'lm_head.bias'
```
I have identified the problem to be with the `"low_cpu_mem_usage": True` flag that `aiserver.py` sets before loading the models (in `maybe_low_cpu_mem_usage()` function), if I edit it to not do that then everything works, though the RAM usage skyrockets and I can barely fit into the ~25G of RAM that I have free during my typical load (total is 32G, ~6G are typically allocated + a bit of buffer to not hit hard limit), so it would be preferable to keep the lower mem if possible.
Curiously, on first load (i.e when model is downloaded) the models seem to be loading fine, not really sure what's up with that, and I don't really want to keep on redownloading ~11G of models every time to experiment.

Setup:
Linux system, virtualenv (with --python=3.8) setup, pip listing:
```
Package            Version
------------------ -------------------
astunparse         1.6.3
bidict             0.22.0
bleach             4.1.0
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.12
click              8.1.2
cmake              3.22.4
dataclasses        0.6
dnspython          2.2.1
eventlet           0.33.0
filelock           3.6.0
Flask              2.1.1
flask-cloudflared  0.0.8
flask-ngrok        0.0.25
Flask-SocketIO     5.1.1
future             0.18.2
greenlet           1.1.2
huggingface-hub    0.5.1
idna               3.3
importlib-metadata 4.11.3
intel-openmp       2022.0.2
itsdangerous       2.1.2
Jinja2             3.1.1
joblib             1.1.0
lupa               1.10
Markdown           3.3.6
MarkupSafe         2.1.1
mkl                2022.0.2
mkl-include        2022.0.2
ninja              1.10.2.3
numpy              1.22.3
packaging          21.3
pip                22.0.4
pycparser          2.21
pyparsing          3.0.8
python-engineio    4.3.1
python-socketio    5.5.2
PyYAML             6.0
regex              2022.3.15
requests           2.27.1
sacremoses         0.0.49
setuptools         61.0.0
six                1.16.0
tbb                2021.5.1
tokenizers         0.12.1
torch              1.12.0a0+git0a5e788
tqdm               4.64.0
transformers       4.18.0
typing_extensions  4.2.0
urllib3            1.26.9
webencodings       0.5.1
Werkzeug           2.1.1
wheel              0.37.1
zipp               3.8.0
```
These are basically what I got from installing the requirements.txt file + custom compiled `torch` (I have a navi AMD GPU, these are not supported by version of ROCm that pytorch ships with). Don't think that `torch` is to blame here as error seems to be in `transformers` module, did I get wrong version?

**Comment by henk717** [comment]
I don't know why that is happening to you and nobody else so i suspect torch 1.12 but either way you are probably better off beta testing our upcoming release which has a completely custom loader and no longer uses lowmem.

Requirements.txt has been edited in that one so double check your versions. I do recommend using our conda environment instead though. You can find those in the environments folder. Because of how low level our new loader in that version is you could run into similar issues. So try getting a hold of pytorch 1.11 since that is the version we currently support.

**Comment by memaddr** [comment]
I have recreated my setup in your repo (py3.8 venv, same custom compiled torch) and everything seems to be working so far, load times are significantly better as well, so I will stay on it for now.
Looking forward to the official release of this version.

The problem is resolved, so I am closing the issue, thanks.
