### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Myuless** [KoboldAI/KoboldAI-Client#110]
Can you tell me what is causing this error?
Welcome to KoboldAI! You have selected the following Model: TPUMeshTransformerGPTJ You have selected the following path for your Model : /content/gpt-j-6b-skein-jax Initializing Flask... OK! Initializing Mesh Transformer JAX, please wait... Traceback (most recent call last): File "aiserver.py", line 1126, in <module> assert vars.model == "TPUMeshTransformerGPTJ" and vars.custmodpth and os.path.isdir(vars.custmodpth) AssertionError

**Comment by henk717** [comment]
I haven't found the exact cause yet since i am unable to produce it myself. It seems to be related to a failed download.

So far no reports in this nature have been made about the upcoming version at https://henk.tech/colabkobold13b so i may have already fixed it in that one.

**Comment by Myuless** [comment]
Thanks for the answer, I'll check it out.
