### ISSUE TITLE
Better Multi-core CPU utilization

### ISSUE THREAD

**Issue by Mine-Modder** [KoboldAI/KoboldAI-Client#125]
My setup looks as follows: I have KoboldAI running in a Ubuntu VM, with 8 cores and 12GB of RAM assigned to it. I run KoboldAI using `./play.sh --host --cpu --lowmem`, and use GPT2 LARGE (4GB) as model. 

Whenever I enter a prompt to generate something, in `htop`, the CPU activity shows that all cores are being utilized for 5 seconds, after which the activity drops to a single core being used for 20 seconds. I am not sure if this is possible, and if so, how difficult it would be to do so, but would it be possible to make this program utilize more CPU cores during the generation phase, making CPU generation faster?

**Comment by henk717** [comment]
In that case I'll close this since it would be something for transformers to improve themselves.
