### ISSUE TITLE
AI error

### ISSUE THREAD

**Issue by Myuless** [KoboldAI/KoboldAI-Client#135]
Nerys 13B V2 writes repetitions how to fix
for example "that's" she says "cool"
"" you "" then "" she ""
"" you""I""""you""you""you""""""""""""""""you""""""""""""""""""""""""

**Comment by henk717** [comment]
Nerys V2 unfortunately can not handle the max 2048. If you lower the tokens to 1900 it should be stable.

**Comment by Myuless** [comment]
How can I find out how to lower it, it's the first time I've come across it?

**Comment by henk717** [comment]
In the settings menu is a maxtoken slider, if you change it from 2048 to something lower and undo the corrupted actions you should get proper outputs again.

**Comment by Myuless** [comment]
ok thanks

**Comment by Myuless** [comment]
and the question is whether this change will be extended to all other models as well ?

**Comment by henk717** [comment]
The settings are specific to the model, I have changed the default setting to be lower to avoid this in the future but if people already have used a model before they won't get the new settings automatically.

**Comment by Myuless** [comment]
OK, thanks for your help.
