### ISSUE TITLE
"ValueError: empty separator" in getnewcontent

### ISSUE THREAD

**Issue by WittyCognomen** [KoboldAI/KoboldAI-Client#14]
`split = txt.split(delim)` fails if `delim` is empty.

Changing [line 806](https://github.com/KoboldAI/KoboldAI-Client/blob/main/aiserver.py#L806) to `split = txt.split(delim) if len(delim) > 0 else [txt]` fixes this.

**Comment by KoboldAI** [comment]
Hello and thanks for the report! I actually just pushed a bugfix update that replaces the string splitting in getnewcontent with a token-based approach, it should resolve this problem!

**Comment by WittyCognomen** [comment]
Cool.
