### ISSUE TITLE
failed to execute pre/post link script for cudatoolkit

### ISSUE THREAD

**Issue by Yimellovzski** [KoboldAI/KoboldAI-Client#149]
Am trying to run koboldAI on my linux machine running Pop!_OS 22.04, I have an Nvidia card so I use CUDA. any idea why this is happening? Here's the output whenever I try running play.sh

./play.sh

bin/micromamba

pytorch/noarch                                       7.9kB @   4.4kB/s  1.8s
pytorch/linux-64                                   171.9kB @  91.5kB/s  1.9s
pkgs/main/linux-64                                   4.7MB @   1.4MB/s  3.3s
pkgs/main/noarch                                   815.5kB @ 204.0kB/s  2.2s
pkgs/r/linux-64                                      1.4MB @ 252.6kB/s  2.4s
pkgs/r/noarch                                        1.3MB @ 228.3kB/s  3.8s
conda-forge/noarch                                   9.1MB @ 491.7kB/s 18.5s
conda-forge/linux-64                                25.0MB @ 254.3kB/s 1m:38.2s

Transaction

  Prefix: runtime/envs/koboldai

  Updating specs:

   - colorama
   - flask-socketio
   - pytorch=1.11
   - python=3.8
   - cudatoolkit=11.1
   - eventlet
   - markdown
   - bleach=4.1.0
   - pip
   - git=2.35.1
   - sentencepiece
   - protobuf

  Package                    Version  Build                        Channel                   Size
───────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                0.1  conda_forge                  conda-forge/linux-64       3kB
  + _openmp_mutex                4.5  2_gnu                        conda-forge/linux-64      24kB
  + bidict                    0.22.0  pyhd8ed1ab_0                 conda-forge/noarch        32kB
  + blas                        2.16  mkl                          conda-forge/linux-64      11kB
  + bleach                     4.1.0  pyhd8ed1ab_0                 conda-forge/noarch       124kB
  + bzip2                      1.0.8  h7f98852_4                   conda-forge/linux-64     496kB
  + c-ares                    1.18.1  h7f98852_0                   conda-forge/linux-64     115kB
  + ca-certificates        2022.6.15  ha878542_0                   conda-forge/linux-64     153kB
  + cffi                      1.15.1  py38h4a40e3a_0               conda-forge/linux-64     234kB
  + click                      8.1.3  py38h578d9bd_0               conda-forge/linux-64     149kB
  + colorama                   0.4.5  pyhd8ed1ab_0                 conda-forge/noarch        19kB
  + cryptography              37.0.1  py38h9ce1e76_0               pkgs/main/linux-64         1MB
  + cudatoolkit               11.1.1  ha002fc5_10                  conda-forge/linux-64       1GB
  + curl                      7.83.1  h2283fc2_0                   conda-forge/linux-64      91kB
  + dnspython                  2.2.1  pyhd8ed1ab_0                 conda-forge/noarch       139kB
  + eventlet                  0.33.1  pyhd8ed1ab_0                 conda-forge/noarch       165kB
  + expat                      2.4.8  h27087fc_0                   conda-forge/linux-64     192kB
  + flask                      2.2.2  pyhd8ed1ab_0                 conda-forge/noarch        76kB
  + flask-socketio             5.3.0  pyhd8ed1ab_0                 conda-forge/noarch        20kB
  + gettext                 0.19.8.1  h73d1719_1008                conda-forge/linux-64       4MB
  + git                       2.35.1  pl5321h04cb727_0             conda-forge/linux-64      14MB
  + greenlet                   1.1.2  py38hfa26641_2               conda-forge/linux-64      93kB
  + idna                         3.3  pyhd8ed1ab_0                 conda-forge/noarch        56kB
  + importlib-metadata        4.11.4  py38h578d9bd_0               conda-forge/linux-64      34kB
  + intel-openmp            2022.0.1  h06a4308_3633                pkgs/main/linux-64         4MB
  + itsdangerous               2.1.2  pyhd8ed1ab_0                 conda-forge/noarch        16kB
  + jinja2                     3.1.2  pyhd8ed1ab_1                 conda-forge/noarch       101kB
  + keyutils                   1.6.1  h166bdaf_0                   conda-forge/linux-64     118kB
  + krb5                      1.19.3  h08a2579_0                   conda-forge/linux-64       2MB
  + ld_impl_linux-64          2.36.1  hea4e1c9_2                   conda-forge/linux-64     683kB
  + libblas                    3.8.0  16_mkl                       conda-forge/linux-64      11kB
  + libcblas                   3.8.0  16_mkl                       conda-forge/linux-64      11kB
  + libcurl                   7.83.1  h2283fc2_0                   conda-forge/linux-64     352kB
  + libedit             3.1.20191231  he28a2e2_2                   conda-forge/linux-64     124kB
  + libev                       4.33  h516909a_1                   conda-forge/linux-64     106kB
  + libffi                     3.4.2  h7f98852_5                   conda-forge/linux-64      58kB
  + libgcc-ng                 12.1.0  h8d9b700_16                  conda-forge/linux-64     963kB
  + libgfortran-ng             7.5.0  h14aa051_20                  conda-forge/linux-64      23kB
  + libgfortran4               7.5.0  h14aa051_20                  conda-forge/linux-64       1MB
  + libgomp                   12.1.0  h8d9b700_16                  conda-forge/linux-64     470kB
  + libiconv                    1.16  h516909a_0                   conda-forge/linux-64       1MB
  + liblapack                  3.8.0  16_mkl                       conda-forge/linux-64      11kB
  + liblapacke                 3.8.0  16_mkl                       conda-forge/linux-64      11kB
  + libnghttp2                1.47.0  hff17c54_1                   conda-forge/linux-64     844kB
  + libnsl                     2.0.0  h7f98852_0                   conda-forge/linux-64      31kB
  + libprotobuf               3.20.1  h6239696_1                   conda-forge/linux-64       3MB
  + libsqlite                 3.39.2  h753d276_1                   conda-forge/linux-64     807kB
  + libssh2                   1.10.0  hf14f497_3                   conda-forge/linux-64     239kB
  + libstdcxx-ng              12.1.0  ha89aaad_16                  conda-forge/linux-64       4MB
  + libuuid                   2.32.1  h7f98852_1000                conda-forge/linux-64      28kB
  + libuv                     1.44.2  h166bdaf_0                   conda-forge/linux-64       1MB
  + libzlib                   1.2.12  h166bdaf_2                   conda-forge/linux-64      65kB
  + markdown                   3.4.1  pyhd8ed1ab_0                 conda-forge/noarch        66kB
  + markupsafe                 2.1.1  py38h0a891b7_1               conda-forge/linux-64      23kB
  + mkl                       2020.2  256                          pkgs/main/linux-64       145MB
  + ncurses                      6.3  h27087fc_1                   conda-forge/linux-64       1MB
  + openssl                    3.0.5  h166bdaf_1                   conda-forge/linux-64       3MB
  + packaging                   21.3  pyhd8ed1ab_0                 conda-forge/noarch        36kB
  + pcre2                      10.37  hc3806b6_1                   conda-forge/linux-64       1MB
  + perl                      5.32.1  2_h7f98852_perl5             conda-forge/linux-64      15MB
  + pip                       22.2.2  pyhd8ed1ab_0                 conda-forge/noarch         2MB
  + protobuf                  3.20.1  py38hfa26641_0               conda-forge/linux-64     340kB
  + pycparser                   2.21  pyhd8ed1ab_0                 conda-forge/noarch       103kB
  + pyopenssl                 22.0.0  pyhd8ed1ab_0                 conda-forge/noarch        50kB
  + pyparsing                  3.0.9  pyhd8ed1ab_0                 conda-forge/noarch        81kB
  + python                    3.8.13  ha86cf86_0_cpython           conda-forge/linux-64      26MB
  + python-engineio            4.3.4  pyhd8ed1ab_0                 conda-forge/noarch        35kB
  + python-socketio            5.7.1  pyhd8ed1ab_0                 conda-forge/noarch        36kB
  + python_abi                   3.8  2_cp38                       conda-forge/linux-64       4kB
  + pytorch                   1.11.0  py3.8_cuda11.1_cudnn8.0.5_0  pytorch/linux-64           1GB
  + pytorch-mutex                1.0  cuda                         pytorch/noarch             3kB
  + readline                   8.1.2  h0f457ee_0                   conda-forge/linux-64     298kB
  + sentencepiece             0.1.96  py38h43d8883_1               conda-forge/linux-64       8MB
  + setuptools                65.2.0  py38h578d9bd_0               conda-forge/linux-64       1MB
  + six                       1.16.0  pyh6c4a22f_0                 conda-forge/noarch        14kB
  + sqlite                    3.39.2  h4ff8645_1                   conda-forge/linux-64     807kB
  + tk                        8.6.12  h27826a3_0                   conda-forge/linux-64       3MB
  + typing_extensions          4.3.0  pyha770c72_0                 conda-forge/noarch        29kB
  + webencodings               0.5.1  py_1                         conda-forge/noarch        12kB
  + werkzeug                   2.2.2  pyhd8ed1ab_0                 conda-forge/noarch       255kB
  + wheel                     0.37.1  pyhd8ed1ab_0                 conda-forge/noarch        32kB
  + xz                         5.2.6  h166bdaf_0                   conda-forge/linux-64     418kB
  + zipp                       3.8.1  pyhd8ed1ab_0                 conda-forge/noarch        13kB
  + zlib                      1.2.12  h166bdaf_2                   conda-forge/linux-64      93kB

  Summary:

  Install: 84 packages

  Total download: 3GB

───────────────────────────────────────────────────────────────────────────────────────────────────

Transaction starting
pytorch-mutex                                        2.9kB @  22.1kB/s  0.1s
_libgcc_mutex                                        2.6kB @  16.9kB/s  0.2s
c-ares                                             115.4kB @ 282.3kB/s  0.3s
keyutils                                           117.8kB @ 138.5kB/s  0.4s
ld_impl_linux-64                                   683.5kB @ 681.9kB/s  1.0s
libgcc-ng                                          962.7kB @ 895.0kB/s  0.9s
libedit                                            123.9kB @  87.9kB/s  0.3s
ncurses                                              1.0MB @ 643.0kB/s  0.7s
libssh2                                            239.4kB @ 132.8kB/s  0.4s
ca-certificates                                    152.8kB @  82.3kB/s  1.9s
bzip2                                              495.7kB @ 211.4kB/s  1.3s
curl                                                91.3kB @  31.4kB/s  0.6s
pcre2                                                1.1MB @ 370.6kB/s  1.2s
wheel                                               32.0kB @   9.6kB/s  0.3s
idna                                                56.1kB @  15.8kB/s  0.2s
bidict                                              31.8kB @   8.5kB/s  0.2s
webencodings                                        11.9kB @   3.0kB/s  0.3s
colorama                                            18.6kB @   4.2kB/s  0.4s
tk                                                   3.5MB @ 761.4kB/s  2.9s
sqlite                                             806.9kB @ 177.2kB/s  2.7s
greenlet                                            92.6kB @  19.8kB/s  0.1s
liblapack                                           10.9kB @   2.3kB/s  0.1s
setuptools                                           1.5MB @ 300.2kB/s  2.1s
blas                                                11.1kB @   2.2kB/s  0.3s
bleach                                             124.1kB @  24.3kB/s  0.7s
markdown                                            66.2kB @  13.0kB/s  0.1s
pyopenssl                                           50.2kB @   9.7kB/s  0.1s
libev                                              106.2kB @  19.6kB/s  0.2s
libgomp                                            470.3kB @  83.1kB/s  0.6s
expat                                              191.8kB @  33.9kB/s  0.2s
libnsl                                              31.2kB @   5.4kB/s  0.1s
cffi                                               234.5kB @  40.4kB/s  1.2s
libzlib                                             64.5kB @  11.1kB/s  0.2s
zlib                                                93.2kB @  15.6kB/s  0.2s
libstdcxx-ng                                         4.5MB @ 725.2kB/s  6.2s
cryptography                                         1.4MB @ 215.9kB/s  1.2s
libcurl                                            352.4kB @  55.5kB/s  0.5s
six                                                 14.3kB @   2.2kB/s  0.2s
python-socketio                                     35.7kB @   5.3kB/s  0.2s
python-engineio                                     35.2kB @   5.1kB/s  0.7s
libcblas                                            10.9kB @   1.5kB/s  0.2s
werkzeug                                           254.6kB @  34.0kB/s  0.4s
pip                                                  1.6MB @ 190.4kB/s  2.0s
libgfortran4                                         1.3MB @ 131.2kB/s  1.8s
libuuid                                             28.3kB @   2.8kB/s  0.2s
xz                                                 418.4kB @  38.4kB/s  0.8s
git                                                 14.0MB @ 795.8kB/s 11.6s
libprotobuf                                          2.7MB @ 136.2kB/s  2.4s
krb5                                                 1.5MB @  70.7kB/s  1.5s
sentencepiece                                        8.4MB @ 382.6kB/s 15.1s
typing_extensions                                   29.2kB @   1.3kB/s  0.2s
packaging                                           36.4kB @   1.6kB/s  0.2s
click                                              149.2kB @   6.6kB/s  0.3s
liblapacke                                          11.0kB @ 478.0 B/s  0.2s
flask-socketio                                      20.4kB @ 883.0 B/s  0.2s
libgfortran-ng                                      23.4kB @   1.0kB/s  0.2s
gettext                                              3.8MB @ 155.1kB/s 18.7s
readline                                           298.1kB @  11.2kB/s  2.1s
libiconv                                             1.4MB @  52.3kB/s  3.9s
intel-openmp                                         4.4MB @ 123.4kB/s 14.1s
itsdangerous                                        16.4kB @ 452.0 B/s  0.6s
protobuf                                           339.7kB @   8.9kB/s  2.2s
dnspython                                          138.8kB @   3.4kB/s  2.2s
libuv                                                1.1MB @  23.2kB/s  5.7s
libnghttp2                                         844.0kB @  16.5kB/s  4.8s
python_abi                                           4.0kB @  78.0 B/s  0.1s
zipp                                                12.9kB @ 251.0 B/s  0.3s
importlib-metadata                                  33.7kB @ 649.0 B/s  0.4s
eventlet                                           164.9kB @   3.1kB/s  1.1s
libffi                                              58.3kB @   1.1kB/s  1.0s
pycparser                                          102.7kB @   1.8kB/s  1.5s
markupsafe                                          22.6kB @ 402.0 B/s  0.4s
_openmp_mutex                                       23.6kB @ 414.0 B/s  1.0s
mkl                                                145.1MB @ 856.4kB/s 2m:22.3s
jinja2                                             101.4kB @ 596.0 B/s  0.6s
pyparsing                                           81.3kB @ 477.0 B/s  0.2s
openssl                                              3.0MB @  17.2kB/s  2.0s
flask                                               75.6kB @ 438.0 B/s  0.1s
libsqlite                                          807.4kB @   4.7kB/s  0.8s
libblas                                             11.2kB @  64.0 B/s  0.1s
perl                                                15.1MB @  82.7kB/s 2m:36.1s
python                                              26.4MB @  84.8kB/s 4m:14.1s
pytorch                                              1.4GB @   1.4MB/s 17m:3.1s
cudatoolkit                                          1.3GB @   2.2MB/s 21m:15.4s
Linking pytorch-mutex-1.0-cuda
Linking _libgcc_mutex-0.1-conda_forge
Linking libstdcxx-ng-12.1.0-ha89aaad_16
Linking ld_impl_linux-64-2.36.1-hea4e1c9_2
Linking ca-certificates-2022.6.15-ha878542_0
Linking libgfortran4-7.5.0-h14aa051_20
Linking libgomp-12.1.0-h8d9b700_16
Linking libgfortran-ng-7.5.0-h14aa051_20
Linking _openmp_mutex-4.5-2_gnu
Linking libgcc-ng-12.1.0-h8d9b700_16
Linking libuuid-2.32.1-h7f98852_1000
Linking libev-4.33-h516909a_1
Linking c-ares-1.18.1-h7f98852_0
Linking libuv-1.44.2-h166bdaf_0
Linking libiconv-1.16-h516909a_0
Linking expat-2.4.8-h27087fc_0
Linking keyutils-1.6.1-h166bdaf_0
Linking xz-5.2.6-h166bdaf_0
Linking openssl-3.0.5-h166bdaf_1
Linking ncurses-6.3-h27087fc_1
Linking libzlib-1.2.12-h166bdaf_2
Linking libffi-3.4.2-h7f98852_5
Linking bzip2-1.0.8-h7f98852_4
Linking cudatoolkit-11.1.1-ha002fc5_10

error    libmamba response code: -1 error message: No such file or directory
critical libmamba failed to execute pre/post link script for cudatoolkit

**Comment by Yimellovzski** [comment]
Update: Turns out running ./play.sh with sudo does the trick, but I wouldn't want it to be the solution, is there any way to run it normally without using sudo every time?

**Comment by vfbd** [comment]
Sorry I don't have any useful insight into this issue, but I am able to run play.sh without superuser privileges. Maybe you have permission issues or internet issues.

**Comment by Yimellovzski** [comment]
With KoboldAI now installed, every time I run `./play.sh` without superuser, it throws `Invalid Argument`
![Screenshot from 2022-08-26 18-28-55](https://user-images.githubusercontent.com/45341995/186998681-583ca979-c041-4b7b-9ec7-76c8c9964df2.png)
