### ISSUE TITLE
Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

### ISSUE THREAD

**Issue by DagothRa** [KoboldAI/KoboldAI-Client#15]
I've followed the setup instructions, and then run through the instructions to enable GPU support. I have a GTX 1080, for reference. I installed CUDA 10.2, which you linked to in your instructions, along with the 2 updates they provided for it. During that installation, I did disable "Geforce Experience" (don't want to use it) and "Graphics Drivers" (I'd rather update those separately) from its installation list, only having it install everything under the CUDA section.
I then got the command line for installing PyTorch with CUDA 10.2 support at that link you provided, which turned out to be:
`pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
I ran that, which looked to have replaced the existing PyTorch which didn't have CUDA support.

However, I get an error when running KoboldAI which indicate's it's not loading CUDA correctly and thus not using my GPU. Example output:
> Model #> 3
> Looking for GPU support...FOUND!
> Use GPU or CPU for generation?:  (Default GPU)
> 
> 1 - GPU
> 2 - CPU
> 
> Mode> 1
> Initializing Flask... OK!
> Initializing transformers, please wait...
> 2021-05-18 19:56:30.807734: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2021-05-18 19:56:30.807837: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> OK! gpt2 pipeline created!
> You may now connect with a browser at http://127.0.0.1:5000/

From the error it looks like it's looking for CUDA 11 instead of CUDA 10? Should I just install CUDA 11.1 and then the appropriate version of PyTorch for that, or...?

**Comment by KoboldAI** [comment]
I've had some folks report this before; it almost always still allows folks to use GPU acceleration (the "Looking for GPU support...FOUND!" in your log means PyTorch is detecting your CUDA install.) I haven't tracked down the source of the issue yet. A couple questions:
1. Do you have finetuneanon's transformers library installed?
2. Start Task Manager, then go to the Performance tab and click on your GPU on the left. Then spin up a model in Kobold. Does the 'Dedicated GPU Memory Usage' gauge increase as the model is initialized?

**Comment by DagothRa** [comment]
1. I haven't installed it separately, no. I saw mention of it in the readme, but nothing about it in your SETUP instructions, so I didn't do anything related to it. Come to think of it, I have briefly run Clover Edition before, but I don't think it installed anything like that globally. I could certainly be wrong about that, though.
2. Hmm, yeah, I see my GPU memory usage jump from 1.0 GB to 2.1 GB when it's loaded with GPT-2, And once I close it, GPU memory usage drops back down to 1.0 GB. So I guess it is working through the GPU.

**Comment by KoboldAI** [comment]
Thanks, just trying to figure out what's injecting the call to CUDA 11. Since PyTorch is installed with an explicit reference to a CUDA version, I'm going to guess it's coming from tensorflow-gpu. When you submit text to the AI, do you get a result back in a few seconds, or closer to 20 seconds?

**Comment by DagothRa** [comment]
It was responding within a second or two when I briefly tested it with GPT-2.

**Comment by KoboldAI** [comment]
Gotcha, that's definitely GPU computed. If you want to get rid of the warning, upgrading to CUDA 11 shouldn't hurt anything, but you'll need to uninstall PyTorch and reinstall it with the CUDA 11 arguments

**Comment by DagothRa** [comment]
Just as a followup, I installed CUDA 11.1 and the associated PyTorch, and it indeed loads without error now, instead outputting a success message at that point.
`2021-05-19 00:17:50.686998: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll`
