### ISSUE TITLE
bugs 

### ISSUE THREAD

**Issue by Myuless** [KoboldAI/KoboldAI-Client#160]
skein 20b started to work poorly and give out phrases unrelated to the story who knows why

**Comment by henk717** [comment]
Is this on official or united? And does switching to the other one fix it?

**Comment by Myuless** [comment]
The official tried to dig in the settings at first all works well and then begins to falter again can anyone suggest what the best settings for 20B ?

**Comment by henk717** [comment]
Official had known tokenizer bugs, should be good now.

**Comment by Myuless** [comment]
Can you also tell me how to remove all torch tensors where to find them thanks in advance

**Comment by henk717** [comment]
Locally you can find them in the models folder, colab does not save them long term.

**Comment by Myuless** [comment]
And another question, so now the models should work more stable

**Comment by henk717** [comment]
For 20B the correct tokenizer is used yes, the other ones have not been changedm

**Comment by Myuless** [comment]
Okay thank you
