### ISSUE TITLE
play.sh produces: ModuleNotFoundError: No module named 'loguru'

### ISSUE THREAD

**Issue by TiagoTiago** [KoboldAI/KoboldAI-Client#164]
When I try running play.sh inside the conda environment, I get this:
```
Traceback (most recent call last):
  File "aiserver.py", line 20, in <module>
    from logger import logger, set_logger_verbosity, quiesce_logger
  File "/home/tt/src/KoboldAI/KoboldAI-Client/logger.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
```
I tried running `pip3 install loguru` but it says requirement already satisfied.

Seems running `python3 ./aiserver.py` directly works though.

I'm on Linux Mint, lemme know what other system info you need.

**Comment by henk717** [comment]
Linux users can update their conda environment with install_requirements.sh , if that doesn't work you can also delete the runtime folder to force an update.

**Comment by TiagoTiago** [comment]
> Linux users can update their conda environment with install_requirements.sh , if that doesn't work you can also delete the runtime folder to force an update.

Hm, that script mentions mamba, I'm not supposed to be using conda anymore?

**Comment by henk717** [comment]
Our own conda environments with play.sh are self contained and use mamba. If you used play.sh that is what it runs. If you prefer to manage your own conda environment you can also update with the environments/huggingface.yml file but in that case you should not use play.sh

**Comment by TiagoTiago** [comment]
Ok
