### ISSUE TITLE
my solution for troubleshooting install / run / "GPU not found"

### ISSUE THREAD

**Issue by fpv999** [KoboldAI/KoboldAI-Client#170]
I've been trying to run it locally with GPU. I followed instructions from README and used install_requirements.bat.
It only worked with CPU, and it complained about not finding \python\condabin\activate
I think something is wrong with play.bat, and it's referencing non-existing dependencies.

Anyway I solved the issue by using full conda with those commands:

```
conda env create -f hugginface.yml (in the folder the file is present)
conda activate koboldai
python aiserver.py
```

**Comment by henk717** [comment]
Existing conda can conflict with ours if you are already in a conda environment by default, so if the manual environment works for you that will be your way to go. The bundled environment especially the one in the offline installer is fully functional for others.

**Comment by fpv999** [comment]
Bundled installer for Windows did not work either.

**Comment by henk717** [comment]
Then your system has dependency conflicts most likely because you have conda in the path. People with conda are indeed best off using the method you have done, this is not something I can change because condas own activation scripts can bug out when other versions of conda are already present.

**Comment by fpv999** [comment]
Sure, it could be just cool to have it in README. I'm a Python rookie, so it was hard for me to find out what's actually happening.
