### ISSUE TITLE
Colab: Stuck at "TPU Backend Compilation Triggered"?

### ISSUE THREAD

**Issue by Derpford** [KoboldAI/KoboldAI-Client#176]
I (finally) got access to a TPU instance, but it's hanging after the model loads. I've been sitting on "TPU backend compilation triggered" for over an hour now.

I'm not sure if this is on Google's end, or what. I tried Erebus 13B and Nerys 13B; Erebus 20B failed due to being out of storage space.

**Comment by henk717** [comment]
Localtunnel was down for a while today, you can best select Cloudflare until their outage is over.

**Comment by Derpford** [comment]
Sadly, I already missed my chance. There's just not enough TPU instances to go around, I guess--even the people who can afford to pay for TPU time are having trouble actually getting it.
