### ISSUE TITLE
Windows Defender SmartScreen preventing install

### ISSUE THREAD

**Issue by KodeMunkie** [KoboldAI/KoboldAI-Client#183]
I've downloaded KobaldAI-1.19-Setup.exe direct from the sourceforge site and Windows Defender SmartScreen prevents it from running showing a dialog that states:

```
Windows protected your PC
Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

Application:  KoboldAI-1.19-Setup.exe
Publisher:  Unknown publisher
```

The dialog can be bypassed with "Run anyway" but without having a publisher and not being a recognised installer makes me apprehensive about running it.

Is it possible to sign this setup exe, (say to help in case of Sourceforge hack, so somebody else can't publish a random binary in your account), and also to somehow have Microsoft recognise the setup executable?

**Comment by henk717** [comment]
It is not possible for me to sign the setup, a suitable certificate requires you to go trough expensive organisation checking and we are not a company neither would it be economically viable for us. I did explore a self signed certificate (Which would not help with smartscreen) but the technology I use for the installer is not compatible. Its effectively a glorified self extractor and the way I embed the data doesn't work anymore if I then also add a certificate to the file.
