### ISSUE TITLE
rocm installation is broken.

### ISSUE THREAD

**Issue by atisharma** [KoboldAI/KoboldAI-Client#189]
It was broken by commit d0cb463c53a8f173ed5f92b1d6913ac8990e0ad5 to environments/rocm.yml https://github.com/KoboldAI/KoboldAI-Client/commit/d0cb463c53a8f173ed5f92b1d6913ac8990e0ad5 which introduced a typo

`ttransformers==4.24.0`

should be 

`transformers==4.24.0`

I would make a pull request but it's literally a single char.

**Comment by henk717** [comment]
Fixed
