### ISSUE TITLE
Running Galactica with KoboldAI

### ISSUE THREAD

**Issue by bale-go** [KoboldAI/KoboldAI-Client#190]
I wanted to check out if I can make facebook/galactica work with KoboldAI.
I managed to run it locally after I switched off the lazy loader. (my working fork with added galactica models: [https://github.com/bale-go/KoboldAI-Client-w--Galactica](https://github.com/bale-go/KoboldAI-Client-w--Galactica) )
However, I couldn't find a simple way to switch lazy-loading off for the colab TPU notebook.
I keep getting the following error for facebook/galactica-6.7b (strangely the similar facebook/opt-6.7b runs just fine):

> 8 TPU cores will be used to run the model.
> 
> Running in OPT compatibility mode.
> 
> 
> 
> 
> 
> This model has   6 662 914 048   parameters.
> 
> Loading model tensors:   0% 0/517 [00:00<?, ?it/s]tcmalloc: large alloc 9958539264 bytes == 0xcb04000 @  0x7f9d020711e7 0x4d30a0 0x5dede2 0x61033f 0x5aab9b 0x47c416 0x6170f1 0x5aaeb9 0x5d9926 0x5d9a1e 0x5efca3 0x4f7916 0x4997a2 0x5d8868 0x4990ca 0x4fe253 0x49abe4 0x55d078 0x5d8941 0x5d8416 0x55f797 0x55d078 0x5d8941 0x4fe318 0x5d8416 0x55f797 0x4fe253 0x49abe4 0x55d078 0x5d8941 0x5d8416
> tcmalloc: large alloc 9958539264 bytes == 0x25ec38000 @  0x7f9d020711e7 0x4d30a0 0x57f16a 0x5dc1e8 0x52dd29 0x5aaeb9 0x4997c7 0x55cd91 0x5d8941 0x4eafcf 0x5d960a 0x502324 0x5efcce 0x4f7916 0x4997a2 0x5d8868 0x4990ca 0x4fe253 0x49abe4 0x55d078 0x5d8941 0x5d8416 0x55f797 0x55d078 0x5d8941 0x4fe318 0x5d8416 0x55f797 0x4fe253 0x49abe4 0x55d078
> tcmalloc: large alloc 9958539264 bytes == 0x4b0d6c000 @  0x7f9d020711e7 0x4d30a0 0x5dede2 0x56ab86 0x56aec4 0x5d9719 0x5d9cb9 0x66fc57 0x64fd2f 0x5dcf51 0x52dd29 0x5aaeb9 0x4997c7 0x55cd91 0x5d8941 0x4eafcf 0x5d960a 0x502324 0x5efcce 0x4f7916 0x4997a2 0x5d8868 0x4990ca 0x4fe253 0x49abe4 0x55d078 0x5d8941 0x5d8416 0x55f797 0x55d078 0x5d8941
> /dev/stdin: line 48:  1183 Killed                  python3 aiserver.py$model$kmpath$configname$ngrok$localtunnel$savemodel --colab

**Comment by henk717** [comment]
The TPU has its own custom backend unique to Kobold, which is why you can't turn that loading off (Its not the lazy loader, its a different routine in the tpu backend).
Support for this model would need to be added in correctly since its probably an unexpected OPT implementation.

**Comment by bale-go** [comment]
I found the problem. It was not the lazy loader per se, but the change from "archive/data/{storage_key}" format to "pytorch_model/data/{storage_key}" format in galactica. After fixing it in tpu_mtj_backend.py, aiserver.py, prompt_tuner.py, torch_lazy_loader.py, the lazy loader started working as intended.
Now the TPU with colab works for facebook/galactica-1.3b but not for facebook/galactica-6.7b (the same "tcmalloc: large alloc" error).

I can make a PR with the galactica related updates, if you're interested.

**Comment by henk717** [comment]
Its slightly more complicated, its not pytorch_model/ its the name of the binfile, for the split files this means it needs to look at a different folder for all of them. If you use the latest United branch (My github) you can take this for a spin, on colab you can change the version to United.

There is one change I have left out and will have to ask VE for his input, but it loads fine for me now including the 6.7B varient.

**Comment by bale-go** [comment]
I tested your branch and it works perfectly with galactica.
Thank you, and keep up the good work! I'm sure this will be very useful for a lot of people.
