### ISSUE TITLE
JSONDecodeError on run

### ISSUE THREAD

**Issue by princessGasmask** [KoboldAI/KoboldAI-Client#2]
When I run through python in command line, I get this error:
![powershell_WJ7lzJHSlZ](https://user-images.githubusercontent.com/5853862/117435135-2078b680-aef3-11eb-86ef-4a5f54808a3a.png)

**Comment by KoboldAI** [comment]
Looks like an error being thrown by the Transformers package while trying to initialize a tokenizer. What model did you pick when trying to run this? There's probably an issue with the vocab file or the config file that came with it.

**Comment by princessGasmask** [comment]
I was attempting to run GPT Neo 1.3B.

**Comment by KoboldAI** [comment]
I don't know enough about the inner workings of Transformers to troubleshoot this too deeply, but I can inquire with HuggingFace. In the meantime, I did a clean download of GPT-Neo-1.3B using transformers and copied everything except for the 5Gb model file into the attached zip. You can try replacing your local files in case there was an issue with your download. These should go in:
C:\Users\<your username>\.cache\huggingface\transformers 
[Neo13B_transformers.zip](https://github.com/KoboldAI/KoboldAI-Client/files/6444156/Neo13B_transformers.zip)

**Comment by princessGasmask** [comment]
This seemed to fix it. Thanks.
