### ISSUE TITLE
Does the Audio for Mobile really works? (Colab)

### ISSUE THREAD

**Issue by etherealxx** [KoboldAI/KoboldAI-Client#209]
So the colab uses [this audio](https://henk.tech/colabkobold/silence.m4a) to make the colab tab stays active. But, that is not the case in my device.  (i'm using Android btw). It's still disconnect anyway after 10ish minute.

Do i need specific browser? or this thing only works on specific Android ROM?

My current workaround is to use Chrome tab feature, and constantly changing my tabs every 5 minutes, waits the colab to refreshes and continue the Kobold stuff.

**Comment by henk717** [comment]
It has been tested on Kiwi browser since that is whar I use, but regular chrome should work to. You want to avoid browsers that actively kill tabs. Of course they would do this anyway if you run out of memory so if you have a very memory constraint phone the trick may not work.

**Comment by etherealxx** [comment]
Have you tested
