### ISSUE TITLE
CPU only proccessing library 

### ISSUE THREAD

**Issue by joshuachris2001** [KoboldAI/KoboldAI-Client#214]
I found a library called ggml for tensorflow models [https://github.com/ggerganov/ggml](https://github.com/ggerganov/ggml). this model can handle gpt-2 and gpt-j tasks on hardware cpu only. from testing on my old workstation it appears quite efficient, but I'm wondering is there a way to connect KoboldAI-Client to ggml as an api or similar.

**Comment by henk717** [comment]
Our entire software is built around huggingface. It would involve writing the entire backend from scratch while the current one already does CPU inference if you put all the layers on the CPU and none on disk cache.
