### ISSUE TITLE
Encoding problem when installing on Windows 10

### ISSUE THREAD

**Issue by BucketCrab** [KoboldAI/KoboldAI-Client#216]
When I run install_requirements.bat, a folder with non standard characters as name, which leads to cudatoolkit to give out error: "No mapping for the Unicode character exists in the target multi-byte code page."

Could anyone help me with this?

**Comment by henk717** [comment]
I have no dirrct control over micromamba bugs, but we provide a premade installer at https://koboldai.org/windows which usually avoids these issues. First try it without the updater and see if that works.

**Comment by BucketCrab** [comment]
It works! For some reason even though I looked for a different install method, I couldn't find anything. Thanks a ton regardless!!
