### ISSUE TITLE
Kodus incorrect. 

### ISSUE THREAD

**Issue by whiteknight6766** [KoboldAI/KoboldAI-Client#224]
Ahoys, 
I believe you have a bug on the back end server of KobaldAI-Horde. I am running the bridge and submitting generations with Bridge and client. While watching my Bridge scroll I notice that "Submitted generation XXXX-XXX-XX--X-X-X and contributed for 3.33" ect... but when I refresh the kobaldai.net/transfer the amount of kudos in my account is only half (and exactly half) of the kudos reported. I have checked the bridge.py but its just logging "for {submit_req.json()["reward"]}'" which means the json I am receiving from the server is saying the wrong kudos amount. 

its a low priorty bug and the kudos aren't for anything in particular, but maybe you forgot to adjust the reply script while balancing the kudos rewards?

**Comment by henk717** [comment]
Half the kudo's go in a reserved fund to become a trusted worker. Once you hit that mark you get them back.

**Comment by whiteknight6766** [comment]
And it's closed, due to the commit. 

but also a misunderstanding of the kudos system may be the result of miscommunication, and may point to an area where documentation needs to be addressed.
