### ISSUE TITLE
Incompatibility with newest Transformers

### ISSUE THREAD

**Issue by smurfhunter** [KoboldAI/KoboldAI-Client#227]
I get the following error on a fresh install of Python 3.19.13, Windows 11, 64 bit. 

ModuleNotFoundError: No module named 'transformers.generation_logits_process'

I resolved it with: pip install transformers==4.20.0

I'm not sure if this is the most recent version that will work, I've been tinkering all day and just kind of got it working and wanted to put in an issue before I forgot tomorrow. It might be 4.25.0 that is the latest working version.

I can provide more info or testing if desired - I didn't see anything in issues or pull requests pertaining to this.

**Comment by henk717** [comment]
This is correct, we officially support Transformers 4.24 and supply environment files and requirements to get suitable dependencies for KoboldAI. If you wish to use a newer transformers you can use the development version available at https://github.com/henk717/koboldai where support for newer transformers versions has been implemented (At the cost of older versions).

For Windows users our own runtime is automatically updated when you use the KoboldAI Updater to the correct versions to use KoboldAI, Linux users can update the runtime with ./install_requirements.sh .

Usage outside our runtimes means the user is responsible for installing the correct compatible versions, as they do breaking changes at times we can not always immediately account for.
