### ISSUE TITLE
where are my models?

### ISSUE THREAD

**Issue by TimyIsCool** [KoboldAI/KoboldAI-Client#252]
So i download some models via the webgui but its not in my models folder so where is it?! 
I have the main install on my F: drive but i think its somewhere on my C: drive since it is eating that up

**Comment by henk717** [comment]
On succesful conversion its in the models folder, until then its in the cache folder. Both are inside Kobolds folder.

**Comment by TimyIsCool** [comment]
it has finished downloading but its not been moved, ive restarted the program and now its not showing in the downloads area where i downloaded it before

**Comment by henk717** [comment]
That can be because you failed the load the model correctly. Typically happens if you did not have enough VRAM. Which can also cause Windows to create a large swap file on your C: drive. Rebooting will fix that one. The size next to the model is the size of vram you need.

**Comment by TimyIsCool** [comment]
is there anyway to load a bigger model that uses say 16gb vram with a 8gb vram gpu? like loading it partly in ram or something?
