### ISSUE TITLE
support for kaggle or paperspace?

### ISSUE THREAD

**Issue by TimyIsCool** [KoboldAI/KoboldAI-Client#253]
Hi, I like google colab but the limits is really annoying. Having it on kaggle and paperspace would be awesome!

**Comment by henk717** [comment]
Both are known to ban Kobold users so we purposefully do not support them officially. It does work on both if you can find a way to set up a tunnel they do not ban.

Typically you can clone the git and then use play.sh --host to get setup, but we can't provide a means to connect to Kobold unfortunately.

**Comment by TimyIsCool** [comment]
on paperspace ive been using cloudflare tunnel fine on it (both trycloudflare and a dedicated tunnel)
what things would i need to change to get it running on paperspace?
