### ISSUE TITLE
"Enter" key does not submit typed message in Pale Moon outside of "Aesthetic Chat UI"

### ISSUE THREAD

**Issue by NintendoManiac64** [KoboldAI/KoboldAI-Client#258]
This occurs on both Windows 7 SP1 and Linux Mint 20.3, and I tested on Windows using a newly-downloaded copy of Pale Moon Portable (see the attached video).

Simply put, the "Enter" key does not work in Pale Moon for submitting the message that you typed when using the "Aesthetic Chat UI".  This issue does not occur in LibreWolf.

More information from https://repo.palemoon.org/MoonchildProductions/UXP/issues/2153

> This is likely because of our change in keypress handling as introduced in [74b3ce90d7](https://repo.palemoon.org/MoonchildProductions/UXP/commit/74b3ce90d73f576a36888c06e413b99b61687b80) that was a response to the bad practice on the web to use onkeypress handlers to attempt to "filter" inputs (instead of using the normal methods available in HTML to do so). We aligned with the behavior in other mainstream browsers in this case even though I considered it webmaster error.

> If websites use onkeypress enter to trigger script processing of a message, then that will likely no longer work, and will need a scripting change on the affected websites.

See the following attached video for a demonstration of the issue (do not mind the messages in the video speaking of an issue with scrolling; I didn't realize at the time that the "autoscroll" setting on Kobold is disabled by default):

[video.webm](https://user-images.githubusercontent.com/11896003/224823392-5d32a606-43df-4088-bd49-640e3c3dff1f.webm)

**Comment by henk717** [comment]
KoboldAI Lite is a seperate product from a different (affiliated) developer, to avoid confusion for the maintainers here please submit it to this github instead so you reach the right person : https://github.com/kaihordewebui/kaihordewebui.github.io
