### ISSUE TITLE
"OpenAI API Error: invalid_request_error" when used with chat GPT 3.5 turbo

### ISSUE THREAD

**Issue by christo-achkov** [KoboldAI/KoboldAI-Client#259]
When using chat GPT3.5 turbo with KoboldAi client I get the following error:
  
`OpenAI API Error: invalid_request_error - This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?`

Does anyone have any ideas?

**Comment by henk717** [comment]
Turbo is currently not implemented in the full KoboldAI, but has been implemented in the browserbased lite.koboldai.net you can select the Custom Endpoint model to get the selection dialogue.

**Comment by christo-achkov** [comment]
Thank you
