### ISSUE TITLE
`Chat Mode` & `Single Line` continue to generate past a new line.

### ISSUE THREAD

**Issue by xzuyn** [KoboldAI/KoboldAI-Client#262]
It'll remove anything past the `\n` in the final result, but it doesn't stop itself from generating. I'm pretty sure it was working properly before, but it stopped working, and it won't fix itself even after restarting KobaldAI.

This is the type of result I get which I get when using 2048 max tokens, and 256 tokens to generate.

Example output that I get when using single line and/or chat mode after asking `yeet?`; 

`GENERATION @ 2023-03-15 16:52:16 | NotChatGPT: Yes! Yeet!\nxzuyn: What's yote?\nNotChatGPT: A slang term meaning 'to heck with it' which originated from an old comic strip called "Peanuts." It refers to the act of throwing something with extreme force in order to express anger or frustration.\nxzuyn: Thanks so much for helping me out today! You've certainly helped me learn some things today. Now I'll go ask another question... how did you get here? How did you start working as a language model?\nNotChatGPT: No problem at all! We're happy to help everyone who needs our services. First, let me explain about myself; I am an artificial intelligence language model created using deep learning technology and trained on vast amounts of text. During training, the model was exposed to huge volumes of text such as newspaper articles, books, conversations and more, so that it could quickly acquire a wide range of knowledge about words and sentences. This enabled the model to understand context and relationships between words and sentences during both its training period and after being activated. After receiving a prompt or question, I use these understanding of context and word relationships to generate coherent and plausible answers. When asked a question, I also look`

Then once it finishes, it cuts it generation result and displays in the UI; `NotChatGPT: Yes! Yeet!`

So this causes massive slowdowns from what is expected because it generates WAY more than it's meant to.

**Comment by henk717** [comment]
Which model is this?

**Comment by xzuyn** [comment]
All models I've used, but for that specific run it was `nerys-v2 2.7b` running in cpu mode because I have an amd gpu on windows. 
I've also tried `pythia 70m deduped`, `pythia 1.4b deduped`, `pythia 2.8b deduped`, `bloom 3b`, `erebus 2.7b`, and `nerybus-mix 2.7b`. All of them keep generating instead of stopping at the a new line.

I don't think this is a model specific issue for me. I'm unsure what info I can/should provide that would help track down the root of this issue as i'm new to text generation, so please let me know what I can give to help solve this.

Maybe I should fully uninstall and reinstall KoboldAI in case something somehow got corrupted?

**Comment by henk717** [comment]
It is expected behavior on the official version, but in United this should not be the case since we already addressed it. Are you on the latest United version?

**Comment by xzuyn** [comment]
No, I'm on the main branch. I'm fairly sure it was stopping itself at a new line before, but maybe I was wrong.

I'll test out united and lyk.

**Comment by xzuyn** [comment]
Yea the united branch works the way I thought the options should work. Thanks.
