### ISSUE TITLE
ColabKoboldGPU: Issued certificate has expired

### ISSUE THREAD

**Issue by brunodpoliveira** [KoboldAI/KoboldAI-Client#272]
Trying to use the ColabGPU gives out the following error:
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by ‘CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US’:
  Issued certificate has expired.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.

adding --no-check-certificate to the wget also does not work, as the process fails further along the line for the same reason

**Comment by henk717** [comment]
This is entirely on githubs end so nothing we can do when this happens, but I heard its already resolved.
