### ISSUE TITLE
Does local support Stable Diffusion?

### ISSUE THREAD

**Issue by OgalFinklestein** [KoboldAI/KoboldAI-Client#275]
I was playing around with https://lite.koboldai.net/ and noticed an option to generate a Stable Diffusion image, which I think is really cool.  However, I didnt see a mention of "diffusion" in the repo's README, so I wonder if that's a feature you're testing out or what?
So can KoboldAI interface with SD (I run Automatic1111's version on Windows)?  If so what needs to be done?

**Comment by NovNovikov** [comment]
You can turn the experimental ui and then you can find it the interface tab. You can select "Use Local stable diffusion" there

**Comment by OgalFinklestein** [comment]
Cool, thanks for the response, I'll have to poke around.  I hope it becomes a **_stable_** feature instead of an experimental one.

**Comment by scavru** [comment]
But the generation does not work properly, It is unclear where he gets the promt, then all the time the beginning of the story, sometimes breaks through further, but it does not work well. It would be nice if the right button would send a selection to the generation.
