### ISSUE TITLE
CPU mode only using half of the capacity availabe

### ISSUE THREAD

**Issue by Akiwuff** [KoboldAI/KoboldAI-Client#288]
I'm running Erebus 6.7 on a 2080, with 8Gb of ram in split mode - 14 layers on the GPU, the rest in disk cache. (Windows 10, Ryzen 6-core CPU, 32Gb of RAM.) When generating, I can see that python is using about 50% of my CPU, and I see no usage of the GPU at all. I know that my setup is less than ideal, but it seems to me that, slow as this might be, it'd be only half as slow if all of the available CPU capacity would be used. Is there any parameter by which I can set the number of threads that should be used?

**Comment by sinabahram** [comment]
Wanted to also +1 this question. Wondering the same thing. How can one pass in the --threads parameter into koboldcpp from this client as the default is 50%?

**Comment by henk717** [comment]
It uses the physical cores not the threads. All behavior is dictated by the backends themselves, outside of Koboldcpp we dont have control over it.
