### ISSUE TITLE
Multiple Sequence Generation Colab Bug

### ISSUE THREAD

**Issue by Flamin513** [KoboldAI/KoboldAI-Client#29]
I'm been trying to use the Multiple Sequence Generation feature that was added and while it does work, it seems like it ends up freezing and not working anymore.

After generating three times or so with the feature on. Colab and KoboldAI both freeze, Colab doesn't appear to receive any info to regenerate while KoboldAI continues to wait for a response that won't come. 

I had the settings for 3 gens per action with 60 tokens, I also had the formatting settings (all of them on), maybe it could be that?
(just checked formatting settings, seems unrelated)

It seems very random when it eventually breaks, I don't know if the colab notebook is bugged or what, I am using the latest notebook for it. 

Replication: 
Use Colab's latest notebook, have it generate a paragraph and then retry a few times. Set 3 generations per action.

It might be the retrying too many times? Not sure. 

Other settings I've had set
0.9 temp - No world info or memory used. - Repetition Penalty was around 1.1 and max tokens 512.

**Comment by Flamin513** [comment]
I'd like to update this and note, it seems that this bug seems to only occur when you retry the action over again which then it gets stuck.

**Comment by henk717** [comment]
Fixed in 0.16
