### ISSUE TITLE
Error occurred during generator call; please check console.

### ISSUE THREAD

**Issue by AnuAnu22** [KoboldAI/KoboldAI-Client#301]
![Screenshot (4)](https://user-images.githubusercontent.com/129385032/233317853-4bbc53b5-8514-4857-b222-0f29b0c5d6b3.png)
When I use **pygmailion ai 1.3B** and write something it gives me this error in console.WHen I use it in **tavern Ai** it shows the same thing .

**Comment by henk717** [comment]
Pygmalion does not support disk cache, if you leave those layers unassigned it will use your CPU ram instead (Which is also faster).

**Comment by AnuAnu22** [comment]
![Uploading Screenshot (5).png…]()
Disk cache is 0 but same thing happens

**Comment by AnuAnu22** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/129385032/233324193-f6ef25ff-1add-456a-a9a4-685ec4fdd445.png)
Disk cache is 0 but same thing happens
