### ISSUE TITLE
Not starting since latest Update

### ISSUE THREAD

**Issue by AsaTyr2018** [KoboldAI/KoboldAI-Client#326]
Good day. i wasn´t updating KoboldAI for a long time. Now i did an Update. Since then its not starting anymore.

I get this message:
The system cannot find the specified file.
Runtime launching in B: drive mode
Traceback (most recent call last):
  File "aiserver.py", line 30, in <module>
    import attention_bias
  File "F:\KoboldAI\attention_bias.py", line 16, in <module>
    import torch
  File "B:\python\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "B:\python\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

I tried the following:
Uninstalling KoboldAI and all its installed dependencys. Redownload the clean Offline Installer. Reinstalled in a different Path (F:\KoboldAI)

Same message.

I´m Using windows 11 Enterprise. Tried running KoboldAI as regular User and as Admin. Nothing works.

Any Ideas?

**Comment by henk717** [comment]
This is because unfortunately Pytorch updates are very unreliable and we increased the Pytorch version on United.
If you run install_requirements.bat and choose 1 for all options you should have it fixed, if not I am also uploading a new offline installer for United in the background.

**Comment by AsaTyr2018** [comment]
> This is because unfortunately Pytorch updates are very unreliable and we increased the Pytorch version on United. If you run install_requirements.bat and choose 1 for all options you should have it fixed, if not I am also uploading a new offline installer for United in the background. Our original can no longer be reliably used for it.

Ok that works well =) Thank you. 
any news when this will work normaly again?

**Comment by henk717** [comment]
The only part that doesn't work as i'd hope is the pytorch package upgrade itself, now you are on 2.0 you should be good for a while as long as you don't downgrade back to main until 2.0 is out. Its the big reinstallations that can screw things up so I tend to be very conservative in these kinds of updates.

**Comment by AsaTyr2018** [comment]
i will keep that in mind. Thank you again =)
