### ISSUE TITLE
Bug: "Retry" deletes multiple steps of the story!

### ISSUE THREAD

**Issue by Bananaman** [KoboldAI/KoboldAI-Client#34]
# My Settings:

- Model GPT Neo 2.7B
- Temperature 0.9
- Top P Sampling 0.8
- Repetition Penalty 2
- Amount to Generate 60
- Max Tokens 2048
- Gens Per Action 1
- W Info Depth 5
- Always Add Prompt YES
- Trim Incomplete Sentences YES
- Remove Blank Lines YES
- Remove Special Characters NO
- Add Sentence Spacing YES

# Steps to Reproduce the Bug:

1. First use my settings above.
2. Type "1." in the prompt and submit it (this is just a random starter seed for the story).
3. Press Submit a few times to generate multiple steps of AI output in the story.
4. Change the "Gens Per Action" setting to 2 or higher.
5. Submit again (blank line) to see two suggestions.
6. Click Retry to re-generate those two suggestions. KoboldAI will now DELETE steps of the story.
7. Every time you click Retry it deletes more and more steps of the story.
8. This bug makes the "Gens Per Action" feature unusable at the moment, but it's a very cool feature so I look forward to using it in the future! :-) ❤️

**Comment by Atkana** [comment]
As mentioned here https://old.reddit.com/r/KoboldAI/comments/nnkbra/koboldai_update_16/gzwymv7/ it's not actually a bug, just a misalignment of user expectations. As also mentioned there, it's planned for the Retry button's functionality to change when there's options to pick, so it can be used for rerolling the multiple options (so you don't have to press submit or accept one then retry to reroll them as you currently do).

**Comment by Bananaman** [comment]
@Atkana Thanks a lot for explaining that. It still confuses me though, because it deletes multiple chunks of the story. The regular Retry (when generation is 1), only redoes the last generated prompt. This one actually deletes the story.

It seems like this thing does:

1. Delete the last story prompt.
2. Re-generate the suggestions for the next prompt (in this case the user never picked one).

Therefore it's a bit of a bug. Basically it deletes the last story prompt to make room for the re-generation, but the user hasn't picked a new generation yet. 🗡️ 

So the bugfix would be something like "if not multi_choice_gui.is_open(): delete the last story prompt" in pseudocode.

Anyway, thank you very much for everything, I am happy to hear it's gonna be fixed.

**Comment by KoboldAI** [comment]
The suggested actions are not actually a part of the story until you select one and the popup list closes (meaning none of the options have been added to the actions array). If you hit Retry while the selections are up, you are retrying the last action in the actions array, which would be the line that the suggestions list is continuing. This also causes the suggestions list to disappear because those continuations are no longer valid (since you're re-rolling the action that those suggestions are continuing). 
As Atkana mentioned, I'll be splitting the Retry button into two modes now depending on whether the suggestions list is up or not in order to eliminate this confusion.

**Comment by Bananaman** [comment]
@KoboldAI Ah gotcha, that makes perfect sense. Glad to hear about the solution. :-)

**Comment by henk717** [comment]
The way retry and back work have been changed in 0.16, let me know if this now behaves as you expect.

**Comment by Bananaman** [comment]
@henk717 I just noticed your message. Thank you SO MUCH. I've done a fresh reinstall of KoboldAI from the latest git and trying it out right now. It's absolutely PERFECT! "Back" closes the multi-selection suggestions without losing the story. "Retry" generates new suggestions without losing the story.

You've done it. It's perfect now! <3 Thank you so much.
