### ISSUE TITLE
Setting up Pygmalion takes wayyyy to long (i dont know if to post it here)

### ISSUE THREAD

**Issue by ttt845h** [KoboldAI/KoboldAI-Client#351]
When i try to set it up it often gets stuck on a percentage, and often takes hours to get up, usually only by 11% each time.
Heres what its on right now: Microsoft Windows [Version 10.0.22621.1848]
(c) Microsoft Corporation. All rights reserved.

C:\KoboldAI\models>git lfs install
Git LFS initialized.

C:\KoboldAI\models>git clone https://huggingface.co/PygmalionAI/pygmalion-7b
Cloning into 'pygmalion-7b'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 29 (delta 5), reused 29 (delta 5), pack-reused 0
Unpacking objects: 100% (29/29), 6.57 KiB | 168.00 KiB/s, done.
Filtering content:  88% (8/9), 3.26 GiB | 2.93 MiB/s

**Comment by henk717** [comment]
Git clone is not related to KoboldAI itself so nothing we can do for you on that front.
