### ISSUE TITLE
Colab - GPU issue

### ISSUE THREAD

**Issue by TheShadOwODevil** [KoboldAI/KoboldAI-Client#353]
Used KoboldAI, and after a few minutes, suddenly, stopped working. Now every time I try to run it, it keeps telling me no GPU is available to use - And my GPU is working fine? Is this like a colab thing?
![image](https://github.com/KoboldAI/KoboldAI-Client/assets/137787761/3cb5dcea-5cec-4900-b326-fdbfbffcf9cc)

**Comment by henk717** [comment]
Colab usage limitation from google, resets over time
