### ISSUE TITLE
ModuleNotFound: Transformer

### ISSUE THREAD

**Issue by Massiveboiler** [KoboldAI/KoboldAI-Client#355]
I am using the Google Colab site, and when it tries to extract the .tar file, it immediately stops, saying 'ModuleNotFoundError Transformer' or something of the like.

Help?

**Comment by Massiveboiler** [comment]
For further information, I am on mobile.
I have also used TavernAI before, though I have deleted all files from it.

**Comment by henk717** [comment]
Our official colab does not extract tar files, make sure you are using either https://koboldai.org/colab or https://koboldai.org/gpucolab if you want to be on an officially supported colab.
