### ISSUE TITLE
error with load models on server/OSError: You seem to have cloned a repository without having git-lfs installed. /_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by kouzhao** [KoboldAI/KoboldAI-Client#357]
i keep getting two errors,
![图片](https://github.com/KoboldAI/KoboldAI-Client/assets/20068083/0244e362-e95c-4c90-ac06-73a2731f489d)
first error
![图片](https://github.com/KoboldAI/KoboldAI-Client/assets/20068083/927cb6aa-761b-415b-ac58-50de45f33433)
second error
![图片](https://github.com/KoboldAI/KoboldAI-Client/assets/20068083/42e2785f-621b-44f4-ba50-5bb88a88dc20)
third
![图片](https://github.com/KoboldAI/KoboldAI-Client/assets/20068083/0316cd54-7fd0-4d68-a88d-6d42fd2faa2d)
fourth

Then the process is stuck.

**Comment by henk717** [comment]
You cloned the model incorrectly (You need git lfs to do that on Linux), if its a 16-bit model use our built in downloader and it will probably do it correctly.
