### ISSUE TITLE
Feature: Implement tail free sampling.

### ISSUE THREAD

**Issue by Bananaman** [KoboldAI/KoboldAI-Client#36]
Not sure if anyone wants to give it a try at implementing this feature. It sounds like an awesome technique for making story-driven AI stay on topic and generate coherent stories:

https://trentbrick.github.io/Tail-Free-Sampling/

It was invented by someone who wanted their D&D generated stories to be on-topic within an overarching narrative, yet be completely original. The paper is fascinating.

**Comment by henk717** [comment]
Implemented in 0.16, you will have to disable TOP_P and TOP_K for it to work properly. The tooltips will guide you in doing so.

**Comment by Bananaman** [comment]
@henk717 Thank you so much, I just tried it out. It was actually a massive difference.

I had set it to 5 generations per attempt.

Before TFS: All 5 suggestions were repetitive and based on something that had already happened in the story. Literal repetition.

After enabling TFS: All 5 suggestions were about logical next steps in the story and were based on the original prompt's overarching plot.

I guess it's working as intended.

By the way am I reading this commit right? I don't see any algorithm, and a closer look for "tfs" in the latest library makes it seem like tail free sampling is a pytorch library feature that you simply had to enable? If so, that's awesome. :) https://github.com/KoboldAI/KoboldAI-Client/commit/72bfc417da2451d10c7970d262c2a4cdf0315e8e

**Comment by henk717** [comment]
Almost, Tail Free Sampling is a feature of the finetune anon fork.
For some of the colab's that use the TPU VE_FORBRYDERNE implemented it from scratch, for the local versions we are borrowing it from finetune's fork until huggingface gets this upstream.

**Comment by Bananaman** [comment]
> Almost, Tail Free Sampling is a feature of the finetune anon fork.

Ah thanks a lot for the deep explanation. And huge thanks to everyone who made this possible!

https://github.com/finetuneanon/transformers
