### ISSUE TITLE
"The system can't find the file, Runtime launching in B: drive mode"

### ISSUE THREAD

**Issue by PotPatPot** [KoboldAI/KoboldAI-Client#364]
![image](https://github.com/KoboldAI/KoboldAI-Client/assets/139664883/0c4900d4-a283-4e3d-8e38-686997efb28f)

The first line is translated to "The system can't find the file"
I have ran requirements.bat as an administrator beforehand, but I keep getting this issue.

**Comment by henk717** [comment]
Your copy of KoboldAI is to old to be installed that way, run the update-koboldai.bat script with Option 1 and it should take care of it.
