### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by Riotas** [KoboldAI/KoboldAI-Client#377]
when i use venus ai with the kobold link the ai repeats sentences over and over again and does not roleplay with me like if i said i punched him the ai will respond with me staring at him with a blank stare really confusing me and messing up my enjoyment with the app please fix this.

**Comment by henk717** [comment]
The AI responses aren't up to us but to the model your using with our software.
Commonly people complaining run small models that are not suitable for chat.
So try something like Gryphe/MythoBoros-13b with United as the version, or perhaps Austism/chronos-hermes-13b-v2 .

**Comment by Riotas** [comment]
how do i install this
