### ISSUE TITLE
colab pygmillion gibbish

### ISSUE THREAD

**Issue by nekohacker591** [KoboldAI/KoboldAI-Client#381]
i get reponses like

kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

or just eijf9w0qf931jf`190irif023if0

random charcter spam

**Comment by nekohacker591** [comment]
![image](https://github.com/KoboldAI/KoboldAI-Client/assets/73713314/70ddbef9-8a71-4026-b405-8539a271512f)

**Comment by henk717** [comment]
Pygmalion is banned on colab, also don't put the context slider over 2048 since the model does not support this.

**Comment by nekohacker591** [comment]
> Pygmalion is banned on colab, also don't put the context slider over 2048 since the model does not support this.

I reupload to bypass The ban

**Comment by henk717** [comment]
Bug is fixed, I still recommend Mythomax instead. Safer for your account and possibly nicer replies.
