### ISSUE TITLE
Changing installation drive letter on Windows

### ISSUE THREAD

**Issue by Yomiia** [KoboldAI/KoboldAI-Client#384]
Kobold installs by default in B: root. My drive B: is already used by my HDD. I can change my HDD to another letter, but it breaks many interactions in my PC. Is there a way to choose the drive letter KoboldAI uses?

**Comment by henk717** [comment]
We only offer a B: drive mode or a subfolder mode, to make use of the subfolder mode make sure that the KoboldAI folder is not in a path that contains spaces (This is wrong: C:\AI Stuff\KoboldAI) and then you can use install_requirements.bat in the mode where it deletes the existing runtime if you have one, followed by the subfolder option.
