### ISSUE TITLE
how to clean up the cache to save space

### ISSUE THREAD

**Issue by Akaryuthered** [KoboldAI/KoboldAI-Client#39]
i decided to use the full precision setting today and its drastically lowered the amount of space left on my hard drive, i'm assuming its storing something on my computer somewhere as i didnt get the space back even after terminating the session, help would be appreciated in cleaning up the space the full precision files took up

**Comment by henk717** [comment]
In the old versions it will be inside the .cache folder in your homefolder (On windows C:\users\username). Newer versions cache is automatically managed and inside the KoboldAI folder.
