### ISSUE TITLE
WinError 193

### ISSUE THREAD

**Issue by mememan629** [KoboldAI/KoboldAI-Client#398]
C:\KoboldAI>play --remote
Runtime launching in B: drive mode

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin B:\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
CUDA SETUP: CUDA runtime path found: B:\python\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary B:\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll...
Colab Check: False, TPU: False
INIT       | OK         | KAI Horde Models
INFO       | __main__:<module>:729 - We loaded the following model backends:
KoboldAI API
KoboldAI Old Colab Method
Basic Huggingface
ExLlama
Huggingface
GooseAI
Legacy GPTQ
Horde
OpenAI
Read Only
INFO       | __main__:general_startup:1444 - Running on Repo: https://github.com/henk717/koboldai Branch:
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
ERROR      | __main__:<module>:11003 - An error has been caught in function '<module>', process 'MainProcess' (308), thread 'MainThread' (16768):
Traceback (most recent call last):

> File "aiserver.py", line 11003, in <module>
    run()
    └ <function run at 0x0000021881F8BD30>

  File "aiserver.py", line 10951, in run
    cloudflare = _run_cloudflared(port)
                 │                └ 5000
                 └ <function _run_cloudflared at 0x0000021881FFDCA0>

  File "B:\python\lib\site-packages\flask_cloudflared.py", line 68, in _run_cloudflared
    _download_cloudflared(cloudflared_path, command)
    │                     │                 └ 'cloudflared-windows-amd64.exe'
    │                     └ 'C:\\Users\\User\\AppData\\Local\\Temp'
    └ <function _download_cloudflared at 0x0000021881FFDD30>

  File "B:\python\lib\site-packages\flask_cloudflared.py", line 100, in _download_cloudflared
    update_cloudflared = subprocess.Popen([(cloudflared_path+'/'+command), 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
                         │          │       │                    │                           │          │
│          └ -2
                         │          │       │                    │                           │          │
└ <module 'subprocess' from 'B:\\python\\lib\\subprocess.py'>
                         │          │       │                    │                           │          └ -3
                         │          │       │                    │                           └ <module 'subprocess' from 'B:\\python\\lib\\subprocess.py'>
                         │          │       │                    └ 'cloudflared-windows-amd64.exe'
                         │          │       └ 'C:\\Users\\User\\AppData\\Local\\Temp'
                         │          └ <class 'eventlet.green.subprocess.Popen'>
                         └ <module 'subprocess' from 'B:\\python\\lib\\subprocess.py'>

  File "B:\python\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    │    │              │     │           │           └ True
    │    │              │     │           └ None
    │    │              │     └ None
    │    │              └ ['C:\\Users\\User\\AppData\\Local\\Temp/cloudflared-windows-amd64.exe', 'update']
    │    └ <function Popen._execute_child at 0x00000218FF846550>
    └ <eventlet.green.subprocess.Popen object at 0x0000021881F8ED00>

  File "B:\python\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       │       │             │           └ 'C:\\Users\\User\\AppData\\Local\\Temp/cloudflared-windows-amd64.exe update'
                       │       │             └ None
                       │       └ <built-in function CreateProcess>
                       └ <module '_winapi' (built-in)>

OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by henk717** [comment]
Cloudflare failed to download correctly, its a file in your temp folder. Deleting it might be enough but if not you can manually download it from here and put it in the same location.

https://github.com/cloudflare/cloudflared/releases/download/2023.8.2/cloudflared-windows-amd64.exe
