### ISSUE TITLE
Installation error saying cannot find HOME

### ISSUE THREAD

**Issue by Belzyenuth** [KoboldAI/KoboldAI-Client#403]
During the installation:
critical libmamba Cannot determine HOME (checked USERPROFILE, HOMEDRIVE and HOMEPATH env vars)

During play.bat, at the start I get this:
The system cannot find the file specified.
Runtime launching in B: drive mode

then I have this final message:
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (B:\python\lib\site-packages\werkzeug\urls.py)
![image_2023-10-04_191522152](https://github.com/KoboldAI/KoboldAI-Client/assets/92762923/8c0df5f6-d41e-4592-8447-b3d1e51a4334)

I tried reinstalling, installing on a different drive, restarting. none of these works. Am I missing something?

I use an AMD GPU but I've ran Kobold Ai perfectly fine in the past.

**Comment by bjlanger** [comment]
Thought I'd toss this here in case anyone else comes looking for a fix: The werkzeug python package had a major update and will no longer work. The last working version is 2.3.7. You can specify this in one of the environment files.
