### ISSUE TITLE
Kobold AI not utilize all cpus

### ISSUE THREAD

**Issue by romi1996** [KoboldAI/KoboldAI-Client#408]
I have a system that has two running CPUs at the same time (36 cores, 72 threads) (2 NUMA Nodes)
Kobold AI mode: CPU Mode only
When running Kobold AI, it seems to just select the second node and run with it, while the first Node is left idle.
Is there anyway to run it on a system that contains more than one CPU?
Thank you.

**Comment by RecoveredApparatus** [comment]
if you are planning to run on bare CPU/CPU only maybe koboldcpp might be a better pick than koboldai as it is meant for CPU usage and also supports formats like gguf.
