### ISSUE TITLE
New line on action

### ISSUE THREAD

**Issue by thaalesalves** [KoboldAI/KoboldAI-Client#41]
I've been playing KoboldAI for some time now, and it's amazing. But one thing that bothers me is that by default when you make an input, it just gets appended to the last line and continues from there. I'd like to suggest adding a configuration that adds a new line when inputs are sent. 

This way it's configurable and both people who like it in the same line and people who don't would have a good and easy playthrough \o/

Thanks! Looking forward to scripting!

**Comment by henk717** [comment]
Do you want to play it as a AI Dungeon like game or do you have a reason to want new lines in a regular story?

If its the first i requested a CYOA mode where it inserts a new line, then adds a > in front of your action and ends with a new link. That format works really well with CYOA models.

If you need it for another purpose and the new line option in formatting is not enough let us know.

**Comment by henk717** [comment]
You can now play it like AI Dungeon by enabling the Adventure Mode in the settings it will then automatically do this formatting if you have it on the Do mode. And it will also block the AI from doing Do's on your behalf.
