### ISSUE TITLE
Slow 

### ISSUE THREAD

**Issue by yourmom-tech** [KoboldAI/KoboldAI-Client#415]
When using KoboldAI Horde on safari or chrome on my iPhone, I type something and it takes forever for KobodAI Horde to respond. It takes so long to type.  What do I do?

**Comment by henk717** [comment]
There are a few things you can do 
- Obtain Kudo's by contributing a GPU to Horde, or participating in the [community](https://koboldai.org/discord).
- Use another solution from us such as the https://koboldai.org/colab.
- Select a queue that has a lower ETA time / use Horde on moments its less crowded.
