### ISSUE TITLE
Encoding problem with accented and special characters

### ISSUE THREAD

**Issue by thaalesalves** [KoboldAI/KoboldAI-Client#42]
Hello! I've gone through two issues here. I was testing a model I finetuned to see if it spoke portuguese well. I imported an AID adventure that had some portuguese in it, and KAI started throwing errors because of the accented characters. I had to write a script that replaces them with their unaccented variation (i.e., ã became a).

Now, I had a similar problem with my CAT<nip> WIs. The triple bar doesn't seem to work with KAI. When the WI is triggered, the character gets messy.

How the WI got inserted into LMI: `Received Data: [ Clavicus Vile description:< name â‰¡ Clavicus Vile& Vile>/< age â‰¡ primeval>. Clavicus Vile summary:< appears â‰¡ male>/< location â‰¡ The Fields of Regret>/< almost always with his hound Barbas by his side>. Clavicus Vile appearance:< skin â‰¡ yellow>/< long black horns>/< eyes â‰¡ red>. Clavicus Vile mental:< jokester& sarcastic& trickster& manipulative>. Clavicus Vile occupation:< Daedric Prince of Trickery and Bargains/ God of Trickery and Bargains>. Clavicus Vile speech:< mocking tone>.]` (`â‰¡` where it should be `≡`)

With the accented character, the error was something like `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 867: character maps to <undefined>enter code here`. After removing all of them, the import worked.

Thanks!

**Comment by NavanBethrax** [comment]
I know its been a year since but i managed to fix the problem.
I opened aiserver.py and looked for the loadRequest function and changed
`open(loadpath, "r")`
to
`open(loadpath, "r",encoding='utf-8')`

**Comment by thaalesalves** [comment]
> I know its been a year since but i managed to fix the problem. I opened aiserver.py and looked for the loadRequest function and changed `open(loadpath, "r")` to `open(loadpath, "r", encoding='utf-8')`

Oh, nice. I had forgotten about that lmao

Thank you!
