### ISSUE TITLE
Micromamba URI can get corrupted by wget [Linux]

### ISSUE THREAD

**Issue by C1oover** [KoboldAI/KoboldAI-Client#423]
wget can corrupt the URI from micromamba it seems as per: mamba-org/mamba#2998
This also affects the "install_requirements.sh". A fix as suggested by the issue in mamba would be to add --no-iri as a wget flag. 
Ex given: `wget --no-iri -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba`

**Comment by henk717** [comment]
Great find thank you!
I thought they were blocking it in the repo for some reason and was waiting for it to be fixed, but thanks to this workaround we don't have to change the dependency to curl.
I have applied it to KoboldAI United (My branch)
