### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Jesseman1** [KoboldAI/KoboldAI-Client#44]
Traceback (most recent call last):
  File "aiserver.py", line 155, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

I got this error after following the instructions to run the program on my GPU. I don't know where to begin to even start fixing this, please help.

**Comment by KoboldAI** [comment]
So that I know what kind of Python environment you're trying to troubleshoot, do you have a miniconda3 folder in your KoboldAI directory?

**Comment by Jesseman1** [comment]
Yes, I have tried following the Absolute Retard's Guide and the install_requirements.bat, I've attempted to install the Torch file at least 4 times now and it still doesn't work. I don't know if this has something to do with trying to install those cuda files earlier or what.

**Comment by Dumpshock** [comment]
Had this issue as well.

I think it might be an issue with a character limit in Windows.  Had mine installed under my User folder Download directory to test things out.  

Once I moved it to another directory (D:\Games in my case) and re-ran the installer, error went away.

**Comment by Jesseman1** [comment]
I have tried uninstalling everything and reinstalling it all over again, I'm still getting the same error. How can I fix this?

**Comment by Dumpshock** [comment]
What is the file path that you have it installed under?

**Comment by Jesseman1** [comment]
> What is the file path that you have it installed under?

The file path is: This PC > 1TB (E:) > KoboldAI > KoboldAI-Client-main
I'm not sure how this would affect anything

**Comment by Jesseman1** [comment]
For all the supporting programs that are needed to run this, I let the PC put them in the default folders.

**Comment by henk717** [comment]
Should be fixed now guys, redownload the latest version and run install_requirements.bat as admin.
It will change your computer to allow the long paths we require and then it will try to download again.

**Comment by Jesseman1** [comment]
After deleting the KoboldAI folder then downloading it and running the install-requirements.bat file as administrator, I got this error message.
![Error](https://user-images.githubusercontent.com/26986519/122484549-d4656b00-cfa2-11eb-86aa-7d8e1389b4b6.jpg)

**Comment by henk717** [comment]
Something got the miniconda3.exe download deleted, or your system was unable to start it for another reason.
Make sure this is not being blocked, or otherwise try downloading it manually from the link you can find in the .bat file.

**Comment by Jesseman1** [comment]
Ok, I finally got some free time to try this again. The AI started up this time, and I could connect to it on my browser. I added some WI, put some memory in, then tried a prompt and got a console error. "LayerNormKernelImpl" not implemented for 'Half'

**Comment by henk717** [comment]
Since you last posted we know a lot of new information about why this is failing.
Until my pull request is approved i recommend downloading the latest version from here : https://github.com/henk717/KoboldAI-Client/tree/mamba

Its installer with the K: drive option will work around the some of the problems you are having since they are caused by the space in your username.

**Comment by Jesseman1** [comment]
I have an Nvidia GTX 1660 with 6GB of VRAM. I'm not sure if this is enough to run the AI.

The original issue seems to be fixed now, since I was able to connect with the AI on my browser with the latest .zip

Is the problem now that I need to enable GPU support for the finetuneanon to function?

**Comment by henk717** [comment]
The problem is that conda can't handle spaces in tge paths and that its downloader often fails the download. If you use that branch i linked it should work as long as you install it in K: drice mode, if it doesn't ill have to change where the temp  folder is because then it trips up on that to.

The issue has always been that its failing its dependencies, you managed to install some but are still missing others.

**Comment by Jesseman1** [comment]
How are you so sure I'm still missing some files? I didn't see any errors during the install this time.
I had deleted the whole KAI folder, then downloaded the .zip from Git yesterday and ran the install as brand new. No errors were given and the console said ready to connect.
On my browser, I connected to the AI and everything seemed to work just fine until I tried to put in a prompt. That's when [ "LayerNormKernelImpl" not implemented for 'Half' ] showed up in the console.

You said that console error is caused by not having GPU support enabled. So then all I need to do now is get GPU support working and KAI should start functioning correctly, right?

I'm sorry if this is redundant, but I just want to make sure we're on the same page. If you think there is still some other file missing from the install, then I'll try that branch, but the whole "needing to install to K drive" sounds like more complications that I don't want to deal with.

**Comment by henk717** [comment]
You need a working CUDA which the installer should have done for you. You can try to install it manually but i can't guarantee everything is compatible if the installer failed.

The K: drive part is all automatic the only thing needed is that you don't already have one. It will map the folder to drive K: to avoid the issue and after a reboot the drive is gone. No permanent changes are made. Another thing you can try is install the game in C:\KoboldAI then the regular method works to.

**Comment by Jesseman1** [comment]
I ran the install from your branch, I'm able to connect with the AI and generate stories just fine now. Thanks!
