### ISSUE TITLE
Trying to set up, but fails: "ModuleNotFoundError: No module named 'eventlet'"

### ISSUE THREAD

**Issue by scenesun** [KoboldAI/KoboldAI-Client#441]
I tried at first using my B: drive (Not a temporary drive), and then my C: drive. However, both have failed in finishing the installation. It tries to get me to get Python with the Microsoft store, but I've tried that way and it didn't work. I also tried getting it from the Python website, too, and while that was better because I could actually find it in my drive, it also didn't fix the issue.

I don't know how to fix this, but I apologize if this is an issue that has already been solved before. To anybody who can offer help, thank you very much! I can offer more information if needed, but from what I see of the code it doesn't seem like it's my hardware that's the problem.

![image-1](https://github.com/KoboldAI/KoboldAI-Client/assets/170485517/d56f6d2d-7dcd-4f18-9bca-7f025c5201ef)

**Comment by henk717** [comment]
I recommend running the development snapshot from https://github.com/henk717/KoboldAI/releases/download/Snapshot-23-01-24/KoboldAI-Setup-20240123.exe if you wish to run this version of KoboldAI.

But it may be better to check our our sister project https://koboldai.org/cpp which is a more modern KoboldAI product that aims to run GGUF models. Its compatible with a wider range of home user hardware.

**Comment by scenesun** [comment]
> I recommend running the development snapshot from https://github.com/henk717/KoboldAI/releases/download/Snapshot-23-01-24/KoboldAI-Setup-20240123.exe if you wish to run this version of KoboldAI.

unfortunately this also doesnt work, as instead it tried to find python and it couldnt for some reason :(
i also dont want to force my boyfriend to run cpp, but im sure if we wanted a better ai dungeon alternative we probably could!
nonetheless, thank you! ill try again later

**Comment by henk717** [comment]
Whats against Koboldcpp? Its a portable file that skips the whole installation. If you are specifically looking for an AI Dungeon alternative its the best one out there.

You can also use it on google colab at https://koboldai.org/colabcpp which by default is configured for the tiefighter model we designed specifically with KoboldAI / KoboldCpp in mind.
