### ISSUE TITLE
Feature Request: Support Ollama API

### ISSUE THREAD

**Issue by BrainSlugs83** [KoboldAI/KoboldAI-Client#444]
Ollama supports serving super fast quantized gguf versions of models, and if we're already invested in that eco system, and have hundreds of GB of models downloaded -- then having to redownload them is really annoying -- and there doesn't seem to be any support in Kobald for quantized models.

If you can add support for calling the ollama api -- where we just provide a hostname and a port, that would be amazing.  Thank you.

**Comment by andy8992** [comment]
That's a bummer of an answer. Especially considering the whole hundreds of models already downloaded thing and the fact nearly all other frontends support ollama now.

**Comment by henk717** [comment]
Ollama uses GGUF in the background, every ollama compatible model has a GGUF version available. If you need some help getting KoboldCpp setup with your favorite model we can help, it will have the necessary modifications to make our UI work optimally and has it included.
