### ISSUE TITLE
Stable UI for Kobold - SDXL crashes due to VRAM (8GB), is there a way to enable flags such as --medvram?

### ISSUE THREAD

**Issue by t4paN** [KoboldAI/KoboldAI-Client#452]
Using koboldcpp-linux-x64-nocuda, Vulkan, Linux Mint, RX 580. 

Steps to reproduce:

Run the -nocuda version

Select any SDXL based model, include VAE or use the VAE fix option

Wait until the image is about to be rendered 

Crash to log-in screen or hard crash that needs a reboot

As the title says, while SD1.5 works amazing well for an AMD, non-ROCM GPU, I am wondering if I could lower the vram requirements so that SDXL runs properly on my system. Some models will run with the vae fix option but it's intermittent and most times it will crash before the final image is rendered regardless of steps used.

**Comment by henk717** [comment]
This is the github of a different KoboldAI product which does not have image generation capability yet.

Please repost on https://koboldai.org/cpp so the right developers can see it.

**Comment by henk717** [comment]
As for a quick answer this seems driver related to me, the compress weights option is the only way to lower vram. In our discord https://koboldai.org/discord the AMD users may be able to assist better since thats where most of them are.
