### ISSUE TITLE
Feature: play.bat takes command line arguments to allow startup automation

### ISSUE THREAD

**Issue by dudethemans** [KoboldAI/KoboldAI-Client#54]
It would be nice for play.bat to be able to take arguments to allow for a single command to skip the startup 'questionnaire', something like `play.bat models/<model> gpu` to start a custom model or `play.bat gpt-2 cpu` to load a default model.  I'm playing around with writing a global command to run Kobold AI and it would be even better if it could get me right to the models loading up and the local server starting without any extra input from me.

**Comment by henk717** [comment]
This is also one of the required steps to make the Colabs use the official version.
There is a workaround by using echo but this does not allow specifying the model location so it won't work with option 8 and 9.

**Comment by henk717** [comment]
Implemented in 0.16, you can use -h as the argument to list all available options.
