### ISSUE TITLE
Notebook automatically stops by performing ctrl-c

### ISSUE THREAD

**Issue by aolko** [KoboldAI/KoboldAI-Client#62]
While attempting to start up koboldai notebook ran for 10 minutes and then `^C` itself. No keystrokes were typed on the user side.
```
Welcome to the KoboldAI Client!
Select an AI model to continue:

Welcome to ColabKobold! The easiest way to run KoboldAI! We will now load the AI, once its done you will see a message to refresh the cloudflare page.
Looking for GPU support...FOUND!
Initializing Flask... OK!
Initializing transformers, please wait...
2021-07-21 12:34:24.124339: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
tcmalloc: large alloc 5302616064 bytes == 0x5605c8c30000 @  0x7f917b37cb6b 0x7f917b39c379 0x7f912076a25e 0x7f912076b9d2 0x7f91627858ed 0x7f91733a7280 0x7f9172fe5d39 0x56043d6dfbf8 0x56043d7536f2 0x56043d74e235 0x56043d6e073a 0x56043d74eb0e 0x56043d74e235 0x56043d6e034b 0x56043d6dfe59 0x56043d82725d 0x56043d796c3b 0x56043d6def01 0x56043d7d0c0d 0x56043d7530d8 0x56043d74e235 0x56043d61fe2c 0x56043d750318 0x56043d74dc35 0x56043d6e073a 0x56043d74f93b 0x56043d74dc35 0x56043d6e073a 0x56043d752f40 0x56043d74dc35 0x56043d74d933
^C
```

Possibly https://github.com/tensorflow/tensorflow/issues/33255
https://github.com/tensorflow/models/issues/7652
https://github.com/huggingface/transformers/issues/4668

**Comment by henk717** [comment]
Was that the 6B model of ColabKobold? If so, this is almost certainly not a KoboldAI problem but a Colab GPU lottery where it crashed for not having enough ram. Trying it again will almost certainly go fine, its Google Colab that automatically terminates them if you hit larger than the resource limit which can happen.

**Comment by aolko** [comment]
[Don't think so](https://colab.research.google.com/drive/1QwjkK_JeK9aYEkyM_6nrJXQARFMnBDmG?usp=sharing)

**Comment by henk717** [comment]
You probably hit a rare instance that didn't have enough memory.
I have reran the Colab you provided and it still works on my end, if you hit a bad Colab instance like this the best thing you can do is terminate your session and see if you can get a better instance going.
Either way its not a bug i can do anything about, its just Colab being Colab.

**Comment by aolko** [comment]
Can you provide more generic ungoogled Jupiter version for running elsewhere? Wanna try other platforms/VPSes

**Comment by aolko** [comment]
Alright, never mind, this can be marked as **WONTFIX**
