### ISSUE TITLE
AI Dungeon selected adventure wrapping after the 9th entry

### ISSUE THREAD

**Issue by ShannonW1950** [KoboldAI/KoboldAI-Client#7]
Linux Mint, Firefox, first time listener and caller.

Just hooked everything up and set it with IK to start testing, and selected a story (the 26th in the list) which properly read in terminal as
`Data recieved:{'cmd': 'importselect', 'data': 'import25'}`

However, it loaded the sixth adventure in the list instead. Suspecting the behavior happening, I tried the 19th adventure, and got the 9th. The 11th adventure got me the first, `import10` becoming `import0` it appears. The terminal log showing data received matches the story I'm clicking, but the client in-browser is wrapping around after 9. I have no warnings or errors other than the statement of being a development server and GPU support not found, but I don't think either are at play here. The issue is happening all the way through to `import68` being read (far as I can tell) as `import8`. 

Not sure how to get debug logs but as far as I can tell my install was fine.

**Comment by KoboldAI** [comment]
Thanks for the report! I just pushed an update that should resolve this, please re-download the client and try again. Post back here if it's still an issue!

**Comment by ShannonW1950** [comment]
Just wanted to check in and say it's fine now!
