### ISSUE TITLE
Saving/Loading Issue

### ISSUE THREAD

**Issue by Flamin513** [KoboldAI/KoboldAI-Client#8]
It seems for odd reasons, I'm unable to save any stories and when I go to load them, it finds nothing.
I am currently using the latest version.

Reproduce issue:
Start a new story prompt, run a few times generation wise and then try to save. The file will "save" but won't be found by the load system.

Solution:
It turns out that the client isn't properly adding the .json extension at the end of the saved files, so they will show up as nothing.

Band-Aid fix is to add the .json extension to the extensionless files and it'll show up and load properly.

**Comment by KoboldAI** [comment]
Thanks for the report! This will be addressed in the bugfix release going out later today.

**Comment by Flamin513** [comment]
Alright! Thank you so much and great client 👍
