### ISSUE TITLE
Authentication error getting access to Google drive storage for colab client

### ISSUE THREAD

**Issue by jpcookie** [KoboldAI/KoboldAI-Client#85]
I'm getting the error 

Authorization Error
Error 400: policy_enforced
Advanced Protection prevented your Google Account from signing in. This security feature stops most non-Google apps and services from accessing your data to keep your account protected.

I'm looking to see if this can be fixed. This was working on this account a week ago.

**Comment by henk717** [comment]
That won't be something under our control, Google did overhaul the sign-in experience for Google Drive so maybe that triggers this security but that is going to be before any of our own code gets executed.

If i understand the error well the administrator that manages your account blocks third-party software and machines from signing in or interacting with your Google account. Which means the Colab machine can't access your google drive anymore (Or if you get it even earlier you might not be able to run Google Colab at all).

The best approach is to double check with which account you are signed in, and if its a personal account, a school account or an office account. If its not a personal account they do have the ability to block your access to what we do. In that case its better to sign out of your work account or use a private browser tab with your private account which won't fall under these restrictions.

If that doesn't work you can also try modifying the colab by removing the drive.mount('/content/drive/') command, but this will limit you to only a few models and will also stop cloud saves and setting storage from working.
