### ISSUE TITLE
Colors in the Windows terminal

### ISSUE THREAD

**Issue by jojorne** [KoboldAI/KoboldAI-Client#87]
You need to call `os.system('color')` at the beginning of the script for the colors to work in the Windows terminal. Otherwise it will display colors like this:
```
←[96mWelcome to the KoboldAI Server!
Select an AI model to continue:←[0m
```

Some people do:
```
import os

#==================================================================#
# Variables & Storage
#==================================================================#

# System call
os.system('')

# Terminal tags for colored text
class colors:
```

**Comment by henk717** [comment]
Thanks for the tip! os.system('color') ended up causing issues on Linux but os.system("") was enough to get it to behave nicely.
I implemented this in the development version, it will be part of the next release.
