### ISSUE TITLE
Use aidg.club API for loading scenarios

### ISSUE THREAD

**Issue by Woruburu** [KoboldAI/KoboldAI-Client#9]
Instead of scraping the HTML (which will be slower and brittle), there is an API endpoint to load scenarios at `https://prompts.aidg.club/api/{id}`.
See the `onLoadClick()` function in the userscript at https://prompts.aidg.club/aidg.user.js for a reference implementation.

**Comment by KoboldAI** [comment]
Replaced HTML scraping with API calls in today's patch, thanks for letting me know about the API!
