### ISSUE TITLE
Auto-save option, and undo-history for edits

### ISSUE THREAD

**Issue by TiagoTiago** [KoboldAI/KoboldAI-Client#94]
I just lost a paragraph because it disappeared right after editing for some reason; then I went to the terminal to copy back what I had written previously, but the muscle memory made me hit Ctrl-C instead of Ctrl-Shift-C, that kills a running program in the terminal instead of copying the selected text. But since I had the browser window still open with the remaining text, I  just booted up Kobold again; but it wiped what I had written completely when it loaded, even in the browser window that was already open from before.

I can still kinda recover the text from the terminal; but the formatting is a bit screwy with all the brackets and escaped characters and stuff; annoying.

It would be great if there was an option to have Kobold automatically save ongoing stories in a temp file or something of the sort, and offer to recover it next time it boots up if it wasn't manually saved before Kobold got closed; and additionally, it would be great to be able to roll back changes, so that if for some reason some part of the text goes bad after editing, you can go back to what it was previously.

ps: Do I need to make this two separate entries, or is it ok to have the whole thing here?

**Comment by henk717** [comment]
Ebolam implemented a autosave feature in the next version of KoboldAI that will be released very soon. Its not this kind of auto recover but its an auto save. For the undo/redo stuff progress is already being made for the version after the next one.

**Comment by henk717** [comment]
Redo and auto saving are now upstreamed.

**Comment by TiagoTiago** [comment]
I'm not sure if I'm using it wrong, but looks like the redo will only revert the "Back" button, and there's still no undo for manual editing (after the editing is completed, or you move the cursor to another action, Ctrl-Z doesn't undo previous edits, and the Back and Redo buttons don't seem to care about edits outside the last state of the action affected by the Back button).

It's not as big deal as it would've been before, since (at least so far) it seems most issues with the editor mode bugging out and eating content randomly have been fixed; but it would still be nice to have a reliable undo/redo history for editing.
